// Mocks generated by Mockito 5.4.6 from annotations
// in shavtzak/test/presentation/bloc/event_bloc_subscription_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:shavtzak/core/constants/calendar_constants.dart' as _i5;
import 'package:shavtzak/core/constants/role_types.dart' as _i7;
import 'package:shavtzak/core/services/drive_service.dart' as _i6;
import 'package:shavtzak/data/repositories/assignment_repository.dart' as _i9;
import 'package:shavtzak/data/repositories/event_repository.dart' as _i3;
import 'package:shavtzak/domain/entities/assignment.dart' as _i8;
import 'package:shavtzak/domain/entities/event.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEvent_0 extends _i1.SmartFake implements _i2.Event {
  _FakeEvent_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [EventRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventRepository extends _i1.Mock implements _i3.EventRepository {
  MockEventRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i2.Event>> watchEvents() => (super.noSuchMethod(
        Invocation.method(
          #watchEvents,
          [],
        ),
        returnValue: _i4.Stream<List<_i2.Event>>.empty(),
      ) as _i4.Stream<List<_i2.Event>>);

  @override
  _i4.Stream<Map<String, _i5.CalendarSyncStatus>>
      watchEventCalendarSyncStates() => (super.noSuchMethod(
            Invocation.method(
              #watchEventCalendarSyncStates,
              [],
            ),
            returnValue:
                _i4.Stream<Map<String, _i5.CalendarSyncStatus>>.empty(),
          ) as _i4.Stream<Map<String, _i5.CalendarSyncStatus>>);

  @override
  _i4.Stream<List<_i2.Event>> watchEventsByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchEventsByDateRange,
          [
            start,
            end,
          ],
        ),
        returnValue: _i4.Stream<List<_i2.Event>>.empty(),
      ) as _i4.Stream<List<_i2.Event>>);

  @override
  _i4.Future<List<_i2.Event>> getAllEvents() => (super.noSuchMethod(
        Invocation.method(
          #getAllEvents,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Event>>.value(<_i2.Event>[]),
      ) as _i4.Future<List<_i2.Event>>);

  @override
  _i4.Future<_i2.Event?> getEventById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getEventById,
          [id],
        ),
        returnValue: _i4.Future<_i2.Event?>.value(),
      ) as _i4.Future<_i2.Event?>);

  @override
  _i4.Future<List<_i2.Event>> getUpcomingEvents() => (super.noSuchMethod(
        Invocation.method(
          #getUpcomingEvents,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Event>>.value(<_i2.Event>[]),
      ) as _i4.Future<List<_i2.Event>>);

  @override
  _i4.Future<List<_i2.Event>> getEventsByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsByDateRange,
          [
            start,
            end,
          ],
        ),
        returnValue: _i4.Future<List<_i2.Event>>.value(<_i2.Event>[]),
      ) as _i4.Future<List<_i2.Event>>);

  @override
  _i4.Future<List<_i2.Event>> getEventsBeforeDate(
    DateTime? cursor, {
    required int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsBeforeDate,
          [cursor],
          {#limit: limit},
        ),
        returnValue: _i4.Future<List<_i2.Event>>.value(<_i2.Event>[]),
      ) as _i4.Future<List<_i2.Event>>);

  @override
  _i4.Future<List<_i2.Event>> getEventsOnDate(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsOnDate,
          [date],
        ),
        returnValue: _i4.Future<List<_i2.Event>>.value(<_i2.Event>[]),
      ) as _i4.Future<List<_i2.Event>>);

  @override
  _i4.Future<bool> isDuplicateEvent(
    String? name,
    DateTime? startDate, {
    String? excludeEventId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #isDuplicateEvent,
          [
            name,
            startDate,
          ],
          {#excludeEventId: excludeEventId},
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i2.Event> createEvent(_i2.Event? event) => (super.noSuchMethod(
        Invocation.method(
          #createEvent,
          [event],
        ),
        returnValue: _i4.Future<_i2.Event>.value(_FakeEvent_0(
          this,
          Invocation.method(
            #createEvent,
            [event],
          ),
        )),
      ) as _i4.Future<_i2.Event>);

  @override
  _i4.Future<_i2.Event> updateEvent(
    _i2.Event? event, {
    _i2.Event? knownOriginal,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEvent,
          [event],
          {#knownOriginal: knownOriginal},
        ),
        returnValue: _i4.Future<_i2.Event>.value(_FakeEvent_0(
          this,
          Invocation.method(
            #updateEvent,
            [event],
            {#knownOriginal: knownOriginal},
          ),
        )),
      ) as _i4.Future<_i2.Event>);

  @override
  _i4.Future<void> deleteEvent(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteEvent,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.DriveFile>> getEventFiles(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventFiles,
          [eventId],
        ),
        returnValue: _i4.Future<List<_i6.DriveFile>>.value(<_i6.DriveFile>[]),
      ) as _i4.Future<List<_i6.DriveFile>>);

  @override
  _i4.Future<List<_i2.Event>> searchEvents(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchEvents,
          [query],
        ),
        returnValue: _i4.Future<List<_i2.Event>>.value(<_i2.Event>[]),
      ) as _i4.Future<List<_i2.Event>>);

  @override
  _i4.Future<List<_i2.Event>> getEventsRequiringRole(_i7.RoleType? role) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsRequiringRole,
          [role],
        ),
        returnValue: _i4.Future<List<_i2.Event>>.value(<_i2.Event>[]),
      ) as _i4.Future<List<_i2.Event>>);

  @override
  _i4.Future<void> importEvents(List<_i2.Event>? events) => (super.noSuchMethod(
        Invocation.method(
          #importEvents,
          [events],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, int>> getStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getStatistics,
          [],
        ),
        returnValue: _i4.Future<Map<String, int>>.value(<String, int>{}),
      ) as _i4.Future<Map<String, int>>);

  @override
  _i4.Future<List<_i2.Event>> getCurrentMonthEvents() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentMonthEvents,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Event>>.value(<_i2.Event>[]),
      ) as _i4.Future<List<_i2.Event>>);

  @override
  _i4.Future<List<_i2.Event>> getThisWeekEvents() => (super.noSuchMethod(
        Invocation.method(
          #getThisWeekEvents,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Event>>.value(<_i2.Event>[]),
      ) as _i4.Future<List<_i2.Event>>);

  @override
  _i4.Future<void> duplicateEvent(
    _i2.Event? originalEvent,
    _i2.Event? newEvent,
    List<_i8.Assignment>? originalAssignments,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #duplicateEvent,
          [
            originalEvent,
            newEvent,
            originalAssignments,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, _i8.Assignment>> duplicateEventWithAssignmentIds(
    _i2.Event? originalEvent,
    _i2.Event? newEvent,
    List<_i8.Assignment>? originalAssignments,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #duplicateEventWithAssignmentIds,
          [
            originalEvent,
            newEvent,
            originalAssignments,
          ],
        ),
        returnValue: _i4.Future<Map<String, _i8.Assignment>>.value(
            <String, _i8.Assignment>{}),
      ) as _i4.Future<Map<String, _i8.Assignment>>);

  @override
  _i4.Future<void> removeAssignmentsAfterDuplication(
          List<String>? assignmentIdsToRemove) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeAssignmentsAfterDuplication,
          [assignmentIdsToRemove],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i6.CreateFolderResult?> ensureDriveFolder(_i2.Event? event) =>
      (super.noSuchMethod(
        Invocation.method(
          #ensureDriveFolder,
          [event],
        ),
        returnValue: _i4.Future<_i6.CreateFolderResult?>.value(),
      ) as _i4.Future<_i6.CreateFolderResult?>);
}

/// A class which mocks [AssignmentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAssignmentRepository extends _i1.Mock
    implements _i9.AssignmentRepository {
  MockAssignmentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i8.Assignment>> watchAssignments() => (super.noSuchMethod(
        Invocation.method(
          #watchAssignments,
          [],
        ),
        returnValue: _i4.Stream<List<_i8.Assignment>>.empty(),
      ) as _i4.Stream<List<_i8.Assignment>>);

  @override
  _i4.Stream<List<_i8.Assignment>> watchAssignmentsByEvent(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAssignmentsByEvent,
          [eventId],
        ),
        returnValue: _i4.Stream<List<_i8.Assignment>>.empty(),
      ) as _i4.Stream<List<_i8.Assignment>>);

  @override
  _i4.Stream<List<_i8.Assignment>> watchAssignmentsByPerson(
          String? teamMemberId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAssignmentsByPerson,
          [teamMemberId],
        ),
        returnValue: _i4.Stream<List<_i8.Assignment>>.empty(),
      ) as _i4.Stream<List<_i8.Assignment>>);

  @override
  _i4.Future<List<_i8.Assignment>> getAllAssignments() => (super.noSuchMethod(
        Invocation.method(
          #getAllAssignments,
          [],
        ),
        returnValue: _i4.Future<List<_i8.Assignment>>.value(<_i8.Assignment>[]),
      ) as _i4.Future<List<_i8.Assignment>>);

  @override
  _i4.Future<_i8.Assignment?> getAssignmentById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssignmentById,
          [id],
        ),
        returnValue: _i4.Future<_i8.Assignment?>.value(),
      ) as _i4.Future<_i8.Assignment?>);

  @override
  _i4.Future<List<_i8.Assignment>> getAssignmentsByEvent(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssignmentsByEvent,
          [eventId],
        ),
        returnValue: _i4.Future<List<_i8.Assignment>>.value(<_i8.Assignment>[]),
      ) as _i4.Future<List<_i8.Assignment>>);

  @override
  _i4.Future<List<_i8.Assignment>> getAssignmentsByPerson(
          String? teamMemberId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssignmentsByPerson,
          [teamMemberId],
        ),
        returnValue: _i4.Future<List<_i8.Assignment>>.value(<_i8.Assignment>[]),
      ) as _i4.Future<List<_i8.Assignment>>);

  @override
  _i4.Future<List<_i8.Assignment>> getAssignmentsByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssignmentsByDateRange,
          [
            start,
            end,
          ],
        ),
        returnValue: _i4.Future<List<_i8.Assignment>>.value(<_i8.Assignment>[]),
      ) as _i4.Future<List<_i8.Assignment>>);

  @override
  _i4.Future<List<_i8.Assignment>> getAssignmentsInTimeWindow({
    required DateTime? windowStart,
    required DateTime? windowEnd,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssignmentsInTimeWindow,
          [],
          {
            #windowStart: windowStart,
            #windowEnd: windowEnd,
          },
        ),
        returnValue: _i4.Future<List<_i8.Assignment>>.value(<_i8.Assignment>[]),
      ) as _i4.Future<List<_i8.Assignment>>);

  @override
  _i4.Future<List<_i8.Assignment>> getAssignmentsByEventIds(
          List<String>? eventIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssignmentsByEventIds,
          [eventIds],
        ),
        returnValue: _i4.Future<List<_i8.Assignment>>.value(<_i8.Assignment>[]),
      ) as _i4.Future<List<_i8.Assignment>>);

  @override
  _i4.Stream<List<_i8.Assignment>> watchAssignmentsInTimeWindow({
    required DateTime? windowStart,
    required DateTime? windowEnd,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAssignmentsInTimeWindow,
          [],
          {
            #windowStart: windowStart,
            #windowEnd: windowEnd,
          },
        ),
        returnValue: _i4.Stream<List<_i8.Assignment>>.empty(),
      ) as _i4.Stream<List<_i8.Assignment>>);

  @override
  _i4.Future<void> createAssignment(_i8.Assignment? assignment) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAssignment,
          [assignment],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> createAssignmentUnchecked(_i8.Assignment? assignment) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAssignmentUnchecked,
          [assignment],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> createAssignmentWithBypass(_i8.Assignment? assignment) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAssignmentWithBypass,
          [assignment],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateAssignment(_i8.Assignment? assignment) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAssignment,
          [assignment],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateAssignmentUnchecked(_i8.Assignment? assignment) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAssignmentUnchecked,
          [assignment],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateAssignmentWithBypass(_i8.Assignment? assignment) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAssignmentWithBypass,
          [assignment],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAssignment(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteAssignment,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAssignmentsBatch(List<String>? assignmentIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAssignmentsBatch,
          [assignmentIds],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveAssignmentsBatch({
    required List<_i8.Assignment>? creates,
    required List<_i8.Assignment>? updates,
    required List<String>? deletes,
    List<({int count, String eventId, String roleType})>? eventQuotaBumps =
        const [],
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAssignmentsBatch,
          [],
          {
            #creates: creates,
            #updates: updates,
            #deletes: deletes,
            #eventQuotaBumps: eventQuotaBumps,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<String>> checkConflicts(_i8.Assignment? assignment) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkConflicts,
          [assignment],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<Map<String, _i9.AssignmentStats>> getEventAssignmentStats(
          String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventAssignmentStats,
          [eventId],
        ),
        returnValue: _i4.Future<Map<String, _i9.AssignmentStats>>.value(
            <String, _i9.AssignmentStats>{}),
      ) as _i4.Future<Map<String, _i9.AssignmentStats>>);

  @override
  _i4.Future<List<_i8.Assignment>> getAssignmentsWithConflicts() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssignmentsWithConflicts,
          [],
        ),
        returnValue: _i4.Future<List<_i8.Assignment>>.value(<_i8.Assignment>[]),
      ) as _i4.Future<List<_i8.Assignment>>);

  @override
  _i4.Future<void> importAssignments(List<_i8.Assignment>? assignments) =>
      (super.noSuchMethod(
        Invocation.method(
          #importAssignments,
          [assignments],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, int>> getStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getStatistics,
          [],
        ),
        returnValue: _i4.Future<Map<String, int>>.value(<String, int>{}),
      ) as _i4.Future<Map<String, int>>);

  @override
  _i4.Future<void> updateAssignmentStatus(
    String? id,
    _i7.AssignmentStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAssignmentStatus,
          [
            id,
            status,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> confirmAssignment(String? id) => (super.noSuchMethod(
        Invocation.method(
          #confirmAssignment,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> declineAssignment(String? id) => (super.noSuchMethod(
        Invocation.method(
          #declineAssignment,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateAssignmentNotes(
    String? id,
    String? notes, {
    String? alternativePhoneNumber,
    String? semanticLabelId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAssignmentNotes,
          [
            id,
            notes,
          ],
          {
            #alternativePhoneNumber: alternativePhoneNumber,
            #semanticLabelId: semanticLabelId,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void cacheCurrentAssignments(List<_i8.Assignment>? assignments) =>
      super.noSuchMethod(
        Invocation.method(
          #cacheCurrentAssignments,
          [assignments],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearCache() => super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i8.Assignment> getCurrentAssignments() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentAssignments,
          [],
        ),
        returnValue: <_i8.Assignment>[],
      ) as List<_i8.Assignment>);
}
