// Mocks generated by Mockito 5.4.6 from annotations
// in shavtzak/test/presentation/bloc/team_bloc_subscription_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:shavtzak/core/constants/role_types.dart' as _i8;
import 'package:shavtzak/data/data_sources/database_interface.dart' as _i2;
import 'package:shavtzak/data/repositories/assignment_repository.dart' as _i6;
import 'package:shavtzak/data/repositories/team_repository.dart' as _i3;
import 'package:shavtzak/domain/entities/assignment.dart' as _i7;
import 'package:shavtzak/domain/entities/team_member.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabaseInterface_0 extends _i1.SmartFake
    implements _i2.DatabaseInterface {
  _FakeDatabaseInterface_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TeamRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTeamRepository extends _i1.Mock implements _i3.TeamRepository {
  MockTeamRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseInterface get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _FakeDatabaseInterface_0(
          this,
          Invocation.getter(#database),
        ),
      ) as _i2.DatabaseInterface);

  @override
  _i4.Stream<List<_i5.TeamMember>> watchTeamMembers() => (super.noSuchMethod(
        Invocation.method(
          #watchTeamMembers,
          [],
        ),
        returnValue: _i4.Stream<List<_i5.TeamMember>>.empty(),
      ) as _i4.Stream<List<_i5.TeamMember>>);

  @override
  _i4.Future<List<_i5.TeamMember>> getAllTeamMembers() => (super.noSuchMethod(
        Invocation.method(
          #getAllTeamMembers,
          [],
        ),
        returnValue: _i4.Future<List<_i5.TeamMember>>.value(<_i5.TeamMember>[]),
      ) as _i4.Future<List<_i5.TeamMember>>);

  @override
  _i4.Future<List<_i5.TeamMember>> getActiveTeamMembers() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveTeamMembers,
          [],
        ),
        returnValue: _i4.Future<List<_i5.TeamMember>>.value(<_i5.TeamMember>[]),
      ) as _i4.Future<List<_i5.TeamMember>>);

  @override
  _i4.Future<_i5.TeamMember?> getTeamMemberById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTeamMemberById,
          [id],
        ),
        returnValue: _i4.Future<_i5.TeamMember?>.value(),
      ) as _i4.Future<_i5.TeamMember?>);

  @override
  _i4.Future<void> createTeamMember(_i5.TeamMember? member) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTeamMember,
          [member],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateTeamMember(_i5.TeamMember? member) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTeamMember,
          [member],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTeamMember(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTeamMember,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deactivateTeamMember(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deactivateTeamMember,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> reactivateTeamMember(String? id) => (super.noSuchMethod(
        Invocation.method(
          #reactivateTeamMember,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.TeamMember>> getTeamMembersByRole(String? roleKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTeamMembersByRole,
          [roleKey],
        ),
        returnValue: _i4.Future<List<_i5.TeamMember>>.value(<_i5.TeamMember>[]),
      ) as _i4.Future<List<_i5.TeamMember>>);

  @override
  _i4.Future<List<_i5.TeamMember>> getAvailableTeamMembers(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableTeamMembers,
          [date],
        ),
        returnValue: _i4.Future<List<_i5.TeamMember>>.value(<_i5.TeamMember>[]),
      ) as _i4.Future<List<_i5.TeamMember>>);

  @override
  _i4.Future<List<_i5.TeamMember>> getQualifiedAvailableMembers(
    String? roleKey,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQualifiedAvailableMembers,
          [
            roleKey,
            date,
          ],
        ),
        returnValue: _i4.Future<List<_i5.TeamMember>>.value(<_i5.TeamMember>[]),
      ) as _i4.Future<List<_i5.TeamMember>>);

  @override
  _i4.Future<List<_i5.TeamMember>> searchTeamMembers(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTeamMembers,
          [query],
        ),
        returnValue: _i4.Future<List<_i5.TeamMember>>.value(<_i5.TeamMember>[]),
      ) as _i4.Future<List<_i5.TeamMember>>);

  @override
  _i4.Future<void> importTeamMembers(List<_i5.TeamMember>? members) =>
      (super.noSuchMethod(
        Invocation.method(
          #importTeamMembers,
          [members],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, int>> getStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getStatistics,
          [],
        ),
        returnValue: _i4.Future<Map<String, int>>.value(<String, int>{}),
      ) as _i4.Future<Map<String, int>>);
}

/// A class which mocks [AssignmentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAssignmentRepository extends _i1.Mock
    implements _i6.AssignmentRepository {
  MockAssignmentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i7.Assignment>> watchAssignments() => (super.noSuchMethod(
        Invocation.method(
          #watchAssignments,
          [],
        ),
        returnValue: _i4.Stream<List<_i7.Assignment>>.empty(),
      ) as _i4.Stream<List<_i7.Assignment>>);

  @override
  _i4.Stream<List<_i7.Assignment>> watchAssignmentsByEvent(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAssignmentsByEvent,
          [eventId],
        ),
        returnValue: _i4.Stream<List<_i7.Assignment>>.empty(),
      ) as _i4.Stream<List<_i7.Assignment>>);

  @override
  _i4.Stream<List<_i7.Assignment>> watchAssignmentsByPerson(
          String? teamMemberId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAssignmentsByPerson,
          [teamMemberId],
        ),
        returnValue: _i4.Stream<List<_i7.Assignment>>.empty(),
      ) as _i4.Stream<List<_i7.Assignment>>);

  @override
  _i4.Future<List<_i7.Assignment>> getAllAssignments() => (super.noSuchMethod(
        Invocation.method(
          #getAllAssignments,
          [],
        ),
        returnValue: _i4.Future<List<_i7.Assignment>>.value(<_i7.Assignment>[]),
      ) as _i4.Future<List<_i7.Assignment>>);

  @override
  _i4.Future<_i7.Assignment?> getAssignmentById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssignmentById,
          [id],
        ),
        returnValue: _i4.Future<_i7.Assignment?>.value(),
      ) as _i4.Future<_i7.Assignment?>);

  @override
  _i4.Future<List<_i7.Assignment>> getAssignmentsByEvent(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssignmentsByEvent,
          [eventId],
        ),
        returnValue: _i4.Future<List<_i7.Assignment>>.value(<_i7.Assignment>[]),
      ) as _i4.Future<List<_i7.Assignment>>);

  @override
  _i4.Future<List<_i7.Assignment>> getAssignmentsByPerson(
          String? teamMemberId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssignmentsByPerson,
          [teamMemberId],
        ),
        returnValue: _i4.Future<List<_i7.Assignment>>.value(<_i7.Assignment>[]),
      ) as _i4.Future<List<_i7.Assignment>>);

  @override
  _i4.Future<List<_i7.Assignment>> getAssignmentsByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssignmentsByDateRange,
          [
            start,
            end,
          ],
        ),
        returnValue: _i4.Future<List<_i7.Assignment>>.value(<_i7.Assignment>[]),
      ) as _i4.Future<List<_i7.Assignment>>);

  @override
  _i4.Future<List<_i7.Assignment>> getAssignmentsInTimeWindow({
    required DateTime? windowStart,
    required DateTime? windowEnd,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssignmentsInTimeWindow,
          [],
          {
            #windowStart: windowStart,
            #windowEnd: windowEnd,
          },
        ),
        returnValue: _i4.Future<List<_i7.Assignment>>.value(<_i7.Assignment>[]),
      ) as _i4.Future<List<_i7.Assignment>>);

  @override
  _i4.Future<List<_i7.Assignment>> getAssignmentsByEventIds(
          List<String>? eventIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssignmentsByEventIds,
          [eventIds],
        ),
        returnValue: _i4.Future<List<_i7.Assignment>>.value(<_i7.Assignment>[]),
      ) as _i4.Future<List<_i7.Assignment>>);

  @override
  _i4.Stream<List<_i7.Assignment>> watchAssignmentsInTimeWindow({
    required DateTime? windowStart,
    required DateTime? windowEnd,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAssignmentsInTimeWindow,
          [],
          {
            #windowStart: windowStart,
            #windowEnd: windowEnd,
          },
        ),
        returnValue: _i4.Stream<List<_i7.Assignment>>.empty(),
      ) as _i4.Stream<List<_i7.Assignment>>);

  @override
  _i4.Future<void> createAssignment(_i7.Assignment? assignment) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAssignment,
          [assignment],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> createAssignmentUnchecked(_i7.Assignment? assignment) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAssignmentUnchecked,
          [assignment],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> createAssignmentWithBypass(_i7.Assignment? assignment) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAssignmentWithBypass,
          [assignment],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateAssignment(_i7.Assignment? assignment) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAssignment,
          [assignment],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateAssignmentUnchecked(_i7.Assignment? assignment) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAssignmentUnchecked,
          [assignment],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateAssignmentWithBypass(_i7.Assignment? assignment) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAssignmentWithBypass,
          [assignment],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAssignment(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteAssignment,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAssignmentsBatch(List<String>? assignmentIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAssignmentsBatch,
          [assignmentIds],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveAssignmentsBatch({
    required List<_i7.Assignment>? creates,
    required List<_i7.Assignment>? updates,
    required List<String>? deletes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAssignmentsBatch,
          [],
          {
            #creates: creates,
            #updates: updates,
            #deletes: deletes,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<String>> checkConflicts(_i7.Assignment? assignment) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkConflicts,
          [assignment],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<Map<String, _i6.AssignmentStats>> getEventAssignmentStats(
          String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventAssignmentStats,
          [eventId],
        ),
        returnValue: _i4.Future<Map<String, _i6.AssignmentStats>>.value(
            <String, _i6.AssignmentStats>{}),
      ) as _i4.Future<Map<String, _i6.AssignmentStats>>);

  @override
  _i4.Future<List<_i7.Assignment>> getAssignmentsWithConflicts() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssignmentsWithConflicts,
          [],
        ),
        returnValue: _i4.Future<List<_i7.Assignment>>.value(<_i7.Assignment>[]),
      ) as _i4.Future<List<_i7.Assignment>>);

  @override
  _i4.Future<void> importAssignments(List<_i7.Assignment>? assignments) =>
      (super.noSuchMethod(
        Invocation.method(
          #importAssignments,
          [assignments],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, int>> getStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getStatistics,
          [],
        ),
        returnValue: _i4.Future<Map<String, int>>.value(<String, int>{}),
      ) as _i4.Future<Map<String, int>>);

  @override
  _i4.Future<void> updateAssignmentStatus(
    String? id,
    _i8.AssignmentStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAssignmentStatus,
          [
            id,
            status,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> confirmAssignment(String? id) => (super.noSuchMethod(
        Invocation.method(
          #confirmAssignment,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> declineAssignment(String? id) => (super.noSuchMethod(
        Invocation.method(
          #declineAssignment,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateAssignmentNotes(
    String? id,
    String? notes, {
    String? alternativePhoneNumber,
    String? semanticLabelId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAssignmentNotes,
          [
            id,
            notes,
          ],
          {
            #alternativePhoneNumber: alternativePhoneNumber,
            #semanticLabelId: semanticLabelId,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void cacheCurrentAssignments(List<_i7.Assignment>? assignments) =>
      super.noSuchMethod(
        Invocation.method(
          #cacheCurrentAssignments,
          [assignments],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearCache() => super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i7.Assignment> getCurrentAssignments() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentAssignments,
          [],
        ),
        returnValue: <_i7.Assignment>[],
      ) as List<_i7.Assignment>);
}
