// Mocks generated by Mockito 5.4.6 from annotations
// in shavtzak/test/presentation/bloc/user_selection_session_lost_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:shavtzak/data/data_sources/database_interface.dart' as _i3;
import 'package:shavtzak/data/repositories/team_repository.dart' as _i8;
import 'package:shavtzak/data/repositories/user_selection_repository.dart'
    as _i4;
import 'package:shavtzak/domain/entities/team_member.dart' as _i2;
import 'package:shavtzak/domain/entities/vehicle_info.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTeamMember_0 extends _i1.SmartFake implements _i2.TeamMember {
  _FakeTeamMember_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseInterface_1 extends _i1.SmartFake
    implements _i3.DatabaseInterface {
  _FakeDatabaseInterface_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserSelectionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserSelectionRepository extends _i1.Mock
    implements _i4.UserSelectionRepository {
  MockUserSelectionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.TeamMember> selectUser(
    String? uniqueKey,
    String? passcode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectUser,
          [
            uniqueKey,
            passcode,
          ],
        ),
        returnValue: _i5.Future<_i2.TeamMember>.value(_FakeTeamMember_0(
          this,
          Invocation.method(
            #selectUser,
            [
              uniqueKey,
              passcode,
            ],
          ),
        )),
      ) as _i5.Future<_i2.TeamMember>);

  @override
  _i5.Future<_i2.TeamMember?> getCachedUser() => (super.noSuchMethod(
        Invocation.method(
          #getCachedUser,
          [],
        ),
        returnValue: _i5.Future<_i2.TeamMember?>.value(),
      ) as _i5.Future<_i2.TeamMember?>);

  @override
  _i5.Future<void> clearUserSelection() => (super.noSuchMethod(
        Invocation.method(
          #clearUserSelection,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> hasCachedUser() => (super.noSuchMethod(
        Invocation.method(
          #hasCachedUser,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<List<_i2.TeamMember>> getAllTeamMembers() => (super.noSuchMethod(
        Invocation.method(
          #getAllTeamMembers,
          [],
        ),
        returnValue: _i5.Future<List<_i2.TeamMember>>.value(<_i2.TeamMember>[]),
      ) as _i5.Future<List<_i2.TeamMember>>);

  @override
  _i5.Future<List<_i2.TeamMember>> searchTeamMembers(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTeamMembers,
          [query],
        ),
        returnValue: _i5.Future<List<_i2.TeamMember>>.value(<_i2.TeamMember>[]),
      ) as _i5.Future<List<_i2.TeamMember>>);

  @override
  _i5.Future<bool> validateUserSelection(String? uniqueKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateUserSelection,
          [uniqueKey],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> verifyTeamMemberPasscode(
    String? uniqueKey,
    String? enteredPasscode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyTeamMemberPasscode,
          [
            uniqueKey,
            enteredPasscode,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setTeamMemberPasscode(
    String? uniqueKey,
    String? passcode,
    int? length, {
    String? currentPasscode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setTeamMemberPasscode,
          [
            uniqueKey,
            passcode,
            length,
          ],
          {#currentPasscode: currentPasscode},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearTeamMemberPasscode(String? uniqueKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearTeamMemberPasscode,
          [uniqueKey],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> getTeamMemberPasscode(String? uniqueKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTeamMemberPasscode,
          [uniqueKey],
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #getTeamMemberPasscode,
            [uniqueKey],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<bool> hasTeamMemberPasscode(String? uniqueKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasTeamMemberPasscode,
          [uniqueKey],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<int?> getTeamMemberPasscodeLength(String? uniqueKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTeamMemberPasscodeLength,
          [uniqueKey],
        ),
        returnValue: _i5.Future<int?>.value(),
      ) as _i5.Future<int?>);

  @override
  _i5.Future<void> updateTeamMemberPhoneNumber(
    String? uniqueKey,
    String? phoneNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTeamMemberPhoneNumber,
          [
            uniqueKey,
            phoneNumber,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateTeamMemberBirthday(
    String? uniqueKey,
    DateTime? birthday,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTeamMemberBirthday,
          [
            uniqueKey,
            birthday,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateTeamMemberVehicleInfo(
    String? uniqueKey,
    _i7.VehicleInfo? vehicleInfo,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTeamMemberVehicleInfo,
          [
            uniqueKey,
            vehicleInfo,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateTeamMemberEmail(
    String? uniqueKey,
    String? email,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTeamMemberEmail,
          [
            uniqueKey,
            email,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [TeamRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTeamRepository extends _i1.Mock implements _i8.TeamRepository {
  MockTeamRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.DatabaseInterface get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _FakeDatabaseInterface_1(
          this,
          Invocation.getter(#database),
        ),
      ) as _i3.DatabaseInterface);

  @override
  _i5.Stream<List<_i2.TeamMember>> watchTeamMembers() => (super.noSuchMethod(
        Invocation.method(
          #watchTeamMembers,
          [],
        ),
        returnValue: _i5.Stream<List<_i2.TeamMember>>.empty(),
      ) as _i5.Stream<List<_i2.TeamMember>>);

  @override
  _i5.Future<List<_i2.TeamMember>> getAllTeamMembers() => (super.noSuchMethod(
        Invocation.method(
          #getAllTeamMembers,
          [],
        ),
        returnValue: _i5.Future<List<_i2.TeamMember>>.value(<_i2.TeamMember>[]),
      ) as _i5.Future<List<_i2.TeamMember>>);

  @override
  _i5.Future<List<_i2.TeamMember>> getActiveTeamMembers() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveTeamMembers,
          [],
        ),
        returnValue: _i5.Future<List<_i2.TeamMember>>.value(<_i2.TeamMember>[]),
      ) as _i5.Future<List<_i2.TeamMember>>);

  @override
  _i5.Future<_i2.TeamMember?> getTeamMemberById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTeamMemberById,
          [id],
        ),
        returnValue: _i5.Future<_i2.TeamMember?>.value(),
      ) as _i5.Future<_i2.TeamMember?>);

  @override
  _i5.Future<void> createTeamMember(_i2.TeamMember? member) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTeamMember,
          [member],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateTeamMember(_i2.TeamMember? member) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTeamMember,
          [member],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteTeamMember(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTeamMember,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deactivateTeamMember(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deactivateTeamMember,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> reactivateTeamMember(String? id) => (super.noSuchMethod(
        Invocation.method(
          #reactivateTeamMember,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.TeamMember>> getTeamMembersByRole(String? roleKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTeamMembersByRole,
          [roleKey],
        ),
        returnValue: _i5.Future<List<_i2.TeamMember>>.value(<_i2.TeamMember>[]),
      ) as _i5.Future<List<_i2.TeamMember>>);

  @override
  _i5.Future<List<_i2.TeamMember>> getAvailableTeamMembers(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableTeamMembers,
          [date],
        ),
        returnValue: _i5.Future<List<_i2.TeamMember>>.value(<_i2.TeamMember>[]),
      ) as _i5.Future<List<_i2.TeamMember>>);

  @override
  _i5.Future<List<_i2.TeamMember>> getQualifiedAvailableMembers(
    String? roleKey,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQualifiedAvailableMembers,
          [
            roleKey,
            date,
          ],
        ),
        returnValue: _i5.Future<List<_i2.TeamMember>>.value(<_i2.TeamMember>[]),
      ) as _i5.Future<List<_i2.TeamMember>>);

  @override
  _i5.Future<List<_i2.TeamMember>> searchTeamMembers(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTeamMembers,
          [query],
        ),
        returnValue: _i5.Future<List<_i2.TeamMember>>.value(<_i2.TeamMember>[]),
      ) as _i5.Future<List<_i2.TeamMember>>);

  @override
  _i5.Future<void> importTeamMembers(List<_i2.TeamMember>? members) =>
      (super.noSuchMethod(
        Invocation.method(
          #importTeamMembers,
          [members],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Map<String, int>> getStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getStatistics,
          [],
        ),
        returnValue: _i5.Future<Map<String, int>>.value(<String, int>{}),
      ) as _i5.Future<Map<String, int>>);
}
