// Mocks generated by Mockito 5.4.6 from annotations
// in shavtzak/test/presentation/widgets/assignment_export_dialog_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:shavtzak/core/constants/calendar_constants.dart' as _i5;
import 'package:shavtzak/core/constants/role_types.dart' as _i8;
import 'package:shavtzak/core/services/drive_service.dart' as _i7;
import 'package:shavtzak/data/repositories/event_repository.dart' as _i3;
import 'package:shavtzak/domain/entities/assignment.dart' as _i9;
import 'package:shavtzak/domain/entities/event.dart' as _i2;
import 'package:shavtzak/domain/entities/slot_annotation.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEvent_0 extends _i1.SmartFake implements _i2.Event {
  _FakeEvent_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [EventRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventRepository extends _i1.Mock implements _i3.EventRepository {
  MockEventRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i2.Event>> watchEvents() => (super.noSuchMethod(
        Invocation.method(
          #watchEvents,
          [],
        ),
        returnValue: _i4.Stream<List<_i2.Event>>.empty(),
      ) as _i4.Stream<List<_i2.Event>>);

  @override
  _i4.Stream<Map<String, _i5.CalendarSyncStatus>>
      watchEventCalendarSyncStates() => (super.noSuchMethod(
            Invocation.method(
              #watchEventCalendarSyncStates,
              [],
            ),
            returnValue:
                _i4.Stream<Map<String, _i5.CalendarSyncStatus>>.empty(),
          ) as _i4.Stream<Map<String, _i5.CalendarSyncStatus>>);

  @override
  _i4.Stream<List<_i2.Event>> watchEventsByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchEventsByDateRange,
          [
            start,
            end,
          ],
        ),
        returnValue: _i4.Stream<List<_i2.Event>>.empty(),
      ) as _i4.Stream<List<_i2.Event>>);

  @override
  _i4.Future<List<_i2.Event>> getAllEvents() => (super.noSuchMethod(
        Invocation.method(
          #getAllEvents,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Event>>.value(<_i2.Event>[]),
      ) as _i4.Future<List<_i2.Event>>);

  @override
  _i4.Future<_i2.Event?> getEventById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getEventById,
          [id],
        ),
        returnValue: _i4.Future<_i2.Event?>.value(),
      ) as _i4.Future<_i2.Event?>);

  @override
  _i4.Future<List<_i2.Event>> getUpcomingEvents() => (super.noSuchMethod(
        Invocation.method(
          #getUpcomingEvents,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Event>>.value(<_i2.Event>[]),
      ) as _i4.Future<List<_i2.Event>>);

  @override
  _i4.Future<List<_i2.Event>> getEventsByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsByDateRange,
          [
            start,
            end,
          ],
        ),
        returnValue: _i4.Future<List<_i2.Event>>.value(<_i2.Event>[]),
      ) as _i4.Future<List<_i2.Event>>);

  @override
  _i4.Future<List<_i2.Event>> getEventsBeforeDate(
    DateTime? cursor, {
    required int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsBeforeDate,
          [cursor],
          {#limit: limit},
        ),
        returnValue: _i4.Future<List<_i2.Event>>.value(<_i2.Event>[]),
      ) as _i4.Future<List<_i2.Event>>);

  @override
  _i4.Future<List<_i2.Event>> getEventsOnDate(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsOnDate,
          [date],
        ),
        returnValue: _i4.Future<List<_i2.Event>>.value(<_i2.Event>[]),
      ) as _i4.Future<List<_i2.Event>>);

  @override
  _i4.Future<bool> isDuplicateEvent(
    String? name,
    DateTime? startDate, {
    String? excludeEventId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #isDuplicateEvent,
          [
            name,
            startDate,
          ],
          {#excludeEventId: excludeEventId},
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i2.Event> createEvent(_i2.Event? event) => (super.noSuchMethod(
        Invocation.method(
          #createEvent,
          [event],
        ),
        returnValue: _i4.Future<_i2.Event>.value(_FakeEvent_0(
          this,
          Invocation.method(
            #createEvent,
            [event],
          ),
        )),
      ) as _i4.Future<_i2.Event>);

  @override
  _i4.Future<_i2.Event> updateEvent(
    _i2.Event? event, {
    _i2.Event? knownOriginal,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEvent,
          [event],
          {#knownOriginal: knownOriginal},
        ),
        returnValue: _i4.Future<_i2.Event>.value(_FakeEvent_0(
          this,
          Invocation.method(
            #updateEvent,
            [event],
            {#knownOriginal: knownOriginal},
          ),
        )),
      ) as _i4.Future<_i2.Event>);

  @override
  _i4.Future<void> updateSlotAnnotation(
    String? eventId,
    String? key,
    _i6.SlotAnnotation? value, {
    String? staleKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSlotAnnotation,
          [
            eventId,
            key,
            value,
          ],
          {#staleKey: staleKey},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteEvent(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteEvent,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.DriveFile>> getEventFiles(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventFiles,
          [eventId],
        ),
        returnValue: _i4.Future<List<_i7.DriveFile>>.value(<_i7.DriveFile>[]),
      ) as _i4.Future<List<_i7.DriveFile>>);

  @override
  _i4.Future<List<_i2.Event>> searchEvents(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchEvents,
          [query],
        ),
        returnValue: _i4.Future<List<_i2.Event>>.value(<_i2.Event>[]),
      ) as _i4.Future<List<_i2.Event>>);

  @override
  _i4.Future<List<_i2.Event>> getEventsRequiringRole(_i8.RoleType? role) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsRequiringRole,
          [role],
        ),
        returnValue: _i4.Future<List<_i2.Event>>.value(<_i2.Event>[]),
      ) as _i4.Future<List<_i2.Event>>);

  @override
  _i4.Future<void> importEvents(List<_i2.Event>? events) => (super.noSuchMethod(
        Invocation.method(
          #importEvents,
          [events],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, int>> getStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getStatistics,
          [],
        ),
        returnValue: _i4.Future<Map<String, int>>.value(<String, int>{}),
      ) as _i4.Future<Map<String, int>>);

  @override
  _i4.Future<List<_i2.Event>> getCurrentMonthEvents() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentMonthEvents,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Event>>.value(<_i2.Event>[]),
      ) as _i4.Future<List<_i2.Event>>);

  @override
  _i4.Future<List<_i2.Event>> getThisWeekEvents() => (super.noSuchMethod(
        Invocation.method(
          #getThisWeekEvents,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Event>>.value(<_i2.Event>[]),
      ) as _i4.Future<List<_i2.Event>>);

  @override
  _i4.Future<void> duplicateEvent(
    _i2.Event? originalEvent,
    _i2.Event? newEvent,
    List<_i9.Assignment>? originalAssignments,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #duplicateEvent,
          [
            originalEvent,
            newEvent,
            originalAssignments,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, _i9.Assignment>> duplicateEventWithAssignmentIds(
    _i2.Event? originalEvent,
    _i2.Event? newEvent,
    List<_i9.Assignment>? originalAssignments,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #duplicateEventWithAssignmentIds,
          [
            originalEvent,
            newEvent,
            originalAssignments,
          ],
        ),
        returnValue: _i4.Future<Map<String, _i9.Assignment>>.value(
            <String, _i9.Assignment>{}),
      ) as _i4.Future<Map<String, _i9.Assignment>>);

  @override
  _i4.Future<void> removeAssignmentsAfterDuplication(
          List<String>? assignmentIdsToRemove) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeAssignmentsAfterDuplication,
          [assignmentIdsToRemove],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i7.CreateFolderResult?> ensureDriveFolder(_i2.Event? event) =>
      (super.noSuchMethod(
        Invocation.method(
          #ensureDriveFolder,
          [event],
        ),
        returnValue: _i4.Future<_i7.CreateFolderResult?>.value(),
      ) as _i4.Future<_i7.CreateFolderResult?>);
}
