// Mocks generated by Mockito 5.4.6 from annotations
// in shavtzak/test/presentation/widgets/event_team_members_dialog_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:shavtzak/core/constants/calendar_constants.dart' as _i9;
import 'package:shavtzak/core/constants/role_types.dart' as _i7;
import 'package:shavtzak/core/services/drive_service.dart' as _i10;
import 'package:shavtzak/data/data_sources/database_interface.dart' as _i3;
import 'package:shavtzak/data/repositories/assignment_repository.dart' as _i4;
import 'package:shavtzak/data/repositories/event_repository.dart' as _i8;
import 'package:shavtzak/data/repositories/role_repository.dart' as _i13;
import 'package:shavtzak/data/repositories/team_repository.dart' as _i11;
import 'package:shavtzak/domain/entities/assignment.dart' as _i6;
import 'package:shavtzak/domain/entities/event.dart' as _i2;
import 'package:shavtzak/domain/entities/role.dart' as _i14;
import 'package:shavtzak/domain/entities/team_member.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEvent_0 extends _i1.SmartFake implements _i2.Event {
  _FakeEvent_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseInterface_1 extends _i1.SmartFake
    implements _i3.DatabaseInterface {
  _FakeDatabaseInterface_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AssignmentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAssignmentRepository extends _i1.Mock
    implements _i4.AssignmentRepository {
  MockAssignmentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<_i6.Assignment>> watchAssignments() => (super.noSuchMethod(
        Invocation.method(
          #watchAssignments,
          [],
        ),
        returnValue: _i5.Stream<List<_i6.Assignment>>.empty(),
      ) as _i5.Stream<List<_i6.Assignment>>);

  @override
  _i5.Stream<List<_i6.Assignment>> watchAssignmentsByEvent(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAssignmentsByEvent,
          [eventId],
        ),
        returnValue: _i5.Stream<List<_i6.Assignment>>.empty(),
      ) as _i5.Stream<List<_i6.Assignment>>);

  @override
  _i5.Stream<List<_i6.Assignment>> watchAssignmentsByPerson(
          String? teamMemberId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAssignmentsByPerson,
          [teamMemberId],
        ),
        returnValue: _i5.Stream<List<_i6.Assignment>>.empty(),
      ) as _i5.Stream<List<_i6.Assignment>>);

  @override
  _i5.Future<List<_i6.Assignment>> getAllAssignments() => (super.noSuchMethod(
        Invocation.method(
          #getAllAssignments,
          [],
        ),
        returnValue: _i5.Future<List<_i6.Assignment>>.value(<_i6.Assignment>[]),
      ) as _i5.Future<List<_i6.Assignment>>);

  @override
  _i5.Future<_i6.Assignment?> getAssignmentById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssignmentById,
          [id],
        ),
        returnValue: _i5.Future<_i6.Assignment?>.value(),
      ) as _i5.Future<_i6.Assignment?>);

  @override
  _i5.Future<List<_i6.Assignment>> getAssignmentsByEvent(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssignmentsByEvent,
          [eventId],
        ),
        returnValue: _i5.Future<List<_i6.Assignment>>.value(<_i6.Assignment>[]),
      ) as _i5.Future<List<_i6.Assignment>>);

  @override
  _i5.Future<List<_i6.Assignment>> getAssignmentsByPerson(
          String? teamMemberId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssignmentsByPerson,
          [teamMemberId],
        ),
        returnValue: _i5.Future<List<_i6.Assignment>>.value(<_i6.Assignment>[]),
      ) as _i5.Future<List<_i6.Assignment>>);

  @override
  _i5.Future<List<_i6.Assignment>> getAssignmentsByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssignmentsByDateRange,
          [
            start,
            end,
          ],
        ),
        returnValue: _i5.Future<List<_i6.Assignment>>.value(<_i6.Assignment>[]),
      ) as _i5.Future<List<_i6.Assignment>>);

  @override
  _i5.Future<List<_i6.Assignment>> getAssignmentsInTimeWindow({
    required DateTime? windowStart,
    required DateTime? windowEnd,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssignmentsInTimeWindow,
          [],
          {
            #windowStart: windowStart,
            #windowEnd: windowEnd,
          },
        ),
        returnValue: _i5.Future<List<_i6.Assignment>>.value(<_i6.Assignment>[]),
      ) as _i5.Future<List<_i6.Assignment>>);

  @override
  _i5.Stream<List<_i6.Assignment>> watchAssignmentsInTimeWindow({
    required DateTime? windowStart,
    required DateTime? windowEnd,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAssignmentsInTimeWindow,
          [],
          {
            #windowStart: windowStart,
            #windowEnd: windowEnd,
          },
        ),
        returnValue: _i5.Stream<List<_i6.Assignment>>.empty(),
      ) as _i5.Stream<List<_i6.Assignment>>);

  @override
  _i5.Future<void> createAssignment(_i6.Assignment? assignment) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAssignment,
          [assignment],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> createAssignmentUnchecked(_i6.Assignment? assignment) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAssignmentUnchecked,
          [assignment],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> createAssignmentWithBypass(_i6.Assignment? assignment) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAssignmentWithBypass,
          [assignment],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateAssignment(_i6.Assignment? assignment) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAssignment,
          [assignment],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateAssignmentUnchecked(_i6.Assignment? assignment) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAssignmentUnchecked,
          [assignment],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateAssignmentWithBypass(_i6.Assignment? assignment) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAssignmentWithBypass,
          [assignment],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteAssignment(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteAssignment,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteAssignmentsBatch(List<String>? assignmentIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAssignmentsBatch,
          [assignmentIds],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<String>> checkConflicts(_i6.Assignment? assignment) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkConflicts,
          [assignment],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<Map<String, _i4.AssignmentStats>> getEventAssignmentStats(
          String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventAssignmentStats,
          [eventId],
        ),
        returnValue: _i5.Future<Map<String, _i4.AssignmentStats>>.value(
            <String, _i4.AssignmentStats>{}),
      ) as _i5.Future<Map<String, _i4.AssignmentStats>>);

  @override
  _i5.Future<List<_i6.Assignment>> getAssignmentsWithConflicts() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssignmentsWithConflicts,
          [],
        ),
        returnValue: _i5.Future<List<_i6.Assignment>>.value(<_i6.Assignment>[]),
      ) as _i5.Future<List<_i6.Assignment>>);

  @override
  _i5.Future<void> importAssignments(List<_i6.Assignment>? assignments) =>
      (super.noSuchMethod(
        Invocation.method(
          #importAssignments,
          [assignments],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Map<String, int>> getStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getStatistics,
          [],
        ),
        returnValue: _i5.Future<Map<String, int>>.value(<String, int>{}),
      ) as _i5.Future<Map<String, int>>);

  @override
  _i5.Future<void> updateAssignmentStatus(
    String? id,
    _i7.AssignmentStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAssignmentStatus,
          [
            id,
            status,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> confirmAssignment(String? id) => (super.noSuchMethod(
        Invocation.method(
          #confirmAssignment,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> declineAssignment(String? id) => (super.noSuchMethod(
        Invocation.method(
          #declineAssignment,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateAssignmentNotes(
    String? id,
    String? notes, {
    String? alternativePhoneNumber,
    String? semanticLabelId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAssignmentNotes,
          [
            id,
            notes,
          ],
          {
            #alternativePhoneNumber: alternativePhoneNumber,
            #semanticLabelId: semanticLabelId,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void cacheCurrentAssignments(List<_i6.Assignment>? assignments) =>
      super.noSuchMethod(
        Invocation.method(
          #cacheCurrentAssignments,
          [assignments],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearCache() => super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i6.Assignment> getCurrentAssignments() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentAssignments,
          [],
        ),
        returnValue: <_i6.Assignment>[],
      ) as List<_i6.Assignment>);
}

/// A class which mocks [EventRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventRepository extends _i1.Mock implements _i8.EventRepository {
  MockEventRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<_i2.Event>> watchEvents() => (super.noSuchMethod(
        Invocation.method(
          #watchEvents,
          [],
        ),
        returnValue: _i5.Stream<List<_i2.Event>>.empty(),
      ) as _i5.Stream<List<_i2.Event>>);

  @override
  _i5.Stream<Map<String, _i9.CalendarSyncStatus>>
      watchEventCalendarSyncStates() => (super.noSuchMethod(
            Invocation.method(
              #watchEventCalendarSyncStates,
              [],
            ),
            returnValue:
                _i5.Stream<Map<String, _i9.CalendarSyncStatus>>.empty(),
          ) as _i5.Stream<Map<String, _i9.CalendarSyncStatus>>);

  @override
  _i5.Stream<List<_i2.Event>> watchEventsByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchEventsByDateRange,
          [
            start,
            end,
          ],
        ),
        returnValue: _i5.Stream<List<_i2.Event>>.empty(),
      ) as _i5.Stream<List<_i2.Event>>);

  @override
  _i5.Future<List<_i2.Event>> getAllEvents() => (super.noSuchMethod(
        Invocation.method(
          #getAllEvents,
          [],
        ),
        returnValue: _i5.Future<List<_i2.Event>>.value(<_i2.Event>[]),
      ) as _i5.Future<List<_i2.Event>>);

  @override
  _i5.Future<_i2.Event?> getEventById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getEventById,
          [id],
        ),
        returnValue: _i5.Future<_i2.Event?>.value(),
      ) as _i5.Future<_i2.Event?>);

  @override
  _i5.Future<List<_i2.Event>> getUpcomingEvents() => (super.noSuchMethod(
        Invocation.method(
          #getUpcomingEvents,
          [],
        ),
        returnValue: _i5.Future<List<_i2.Event>>.value(<_i2.Event>[]),
      ) as _i5.Future<List<_i2.Event>>);

  @override
  _i5.Future<List<_i2.Event>> getEventsByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsByDateRange,
          [
            start,
            end,
          ],
        ),
        returnValue: _i5.Future<List<_i2.Event>>.value(<_i2.Event>[]),
      ) as _i5.Future<List<_i2.Event>>);

  @override
  _i5.Future<List<_i2.Event>> getEventsOnDate(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsOnDate,
          [date],
        ),
        returnValue: _i5.Future<List<_i2.Event>>.value(<_i2.Event>[]),
      ) as _i5.Future<List<_i2.Event>>);

  @override
  _i5.Future<bool> isDuplicateEvent(
    String? name,
    DateTime? startDate, {
    String? excludeEventId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #isDuplicateEvent,
          [
            name,
            startDate,
          ],
          {#excludeEventId: excludeEventId},
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i2.Event> createEvent(_i2.Event? event) => (super.noSuchMethod(
        Invocation.method(
          #createEvent,
          [event],
        ),
        returnValue: _i5.Future<_i2.Event>.value(_FakeEvent_0(
          this,
          Invocation.method(
            #createEvent,
            [event],
          ),
        )),
      ) as _i5.Future<_i2.Event>);

  @override
  _i5.Future<_i2.Event> updateEvent(_i2.Event? event) => (super.noSuchMethod(
        Invocation.method(
          #updateEvent,
          [event],
        ),
        returnValue: _i5.Future<_i2.Event>.value(_FakeEvent_0(
          this,
          Invocation.method(
            #updateEvent,
            [event],
          ),
        )),
      ) as _i5.Future<_i2.Event>);

  @override
  _i5.Future<void> deleteEvent(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteEvent,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i10.DriveFile>> getEventFiles(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventFiles,
          [eventId],
        ),
        returnValue: _i5.Future<List<_i10.DriveFile>>.value(<_i10.DriveFile>[]),
      ) as _i5.Future<List<_i10.DriveFile>>);

  @override
  _i5.Future<List<_i2.Event>> searchEvents(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchEvents,
          [query],
        ),
        returnValue: _i5.Future<List<_i2.Event>>.value(<_i2.Event>[]),
      ) as _i5.Future<List<_i2.Event>>);

  @override
  _i5.Future<List<_i2.Event>> getEventsRequiringRole(_i7.RoleType? role) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsRequiringRole,
          [role],
        ),
        returnValue: _i5.Future<List<_i2.Event>>.value(<_i2.Event>[]),
      ) as _i5.Future<List<_i2.Event>>);

  @override
  _i5.Future<void> importEvents(List<_i2.Event>? events) => (super.noSuchMethod(
        Invocation.method(
          #importEvents,
          [events],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Map<String, int>> getStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getStatistics,
          [],
        ),
        returnValue: _i5.Future<Map<String, int>>.value(<String, int>{}),
      ) as _i5.Future<Map<String, int>>);

  @override
  _i5.Future<List<_i2.Event>> getCurrentMonthEvents() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentMonthEvents,
          [],
        ),
        returnValue: _i5.Future<List<_i2.Event>>.value(<_i2.Event>[]),
      ) as _i5.Future<List<_i2.Event>>);

  @override
  _i5.Future<List<_i2.Event>> getThisWeekEvents() => (super.noSuchMethod(
        Invocation.method(
          #getThisWeekEvents,
          [],
        ),
        returnValue: _i5.Future<List<_i2.Event>>.value(<_i2.Event>[]),
      ) as _i5.Future<List<_i2.Event>>);

  @override
  _i5.Future<void> duplicateEvent(
    _i2.Event? originalEvent,
    _i2.Event? newEvent,
    List<_i6.Assignment>? originalAssignments,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #duplicateEvent,
          [
            originalEvent,
            newEvent,
            originalAssignments,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Map<String, _i6.Assignment>> duplicateEventWithAssignmentIds(
    _i2.Event? originalEvent,
    _i2.Event? newEvent,
    List<_i6.Assignment>? originalAssignments,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #duplicateEventWithAssignmentIds,
          [
            originalEvent,
            newEvent,
            originalAssignments,
          ],
        ),
        returnValue: _i5.Future<Map<String, _i6.Assignment>>.value(
            <String, _i6.Assignment>{}),
      ) as _i5.Future<Map<String, _i6.Assignment>>);

  @override
  _i5.Future<void> removeAssignmentsAfterDuplication(
          List<String>? assignmentIdsToRemove) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeAssignmentsAfterDuplication,
          [assignmentIdsToRemove],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i10.CreateFolderResult?> ensureDriveFolder(_i2.Event? event) =>
      (super.noSuchMethod(
        Invocation.method(
          #ensureDriveFolder,
          [event],
        ),
        returnValue: _i5.Future<_i10.CreateFolderResult?>.value(),
      ) as _i5.Future<_i10.CreateFolderResult?>);
}

/// A class which mocks [TeamRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTeamRepository extends _i1.Mock implements _i11.TeamRepository {
  MockTeamRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.DatabaseInterface get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _FakeDatabaseInterface_1(
          this,
          Invocation.getter(#database),
        ),
      ) as _i3.DatabaseInterface);

  @override
  _i5.Stream<List<_i12.TeamMember>> watchTeamMembers() => (super.noSuchMethod(
        Invocation.method(
          #watchTeamMembers,
          [],
        ),
        returnValue: _i5.Stream<List<_i12.TeamMember>>.empty(),
      ) as _i5.Stream<List<_i12.TeamMember>>);

  @override
  _i5.Future<List<_i12.TeamMember>> getAllTeamMembers() => (super.noSuchMethod(
        Invocation.method(
          #getAllTeamMembers,
          [],
        ),
        returnValue:
            _i5.Future<List<_i12.TeamMember>>.value(<_i12.TeamMember>[]),
      ) as _i5.Future<List<_i12.TeamMember>>);

  @override
  _i5.Future<List<_i12.TeamMember>> getActiveTeamMembers() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveTeamMembers,
          [],
        ),
        returnValue:
            _i5.Future<List<_i12.TeamMember>>.value(<_i12.TeamMember>[]),
      ) as _i5.Future<List<_i12.TeamMember>>);

  @override
  _i5.Future<_i12.TeamMember?> getTeamMemberById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTeamMemberById,
          [id],
        ),
        returnValue: _i5.Future<_i12.TeamMember?>.value(),
      ) as _i5.Future<_i12.TeamMember?>);

  @override
  _i5.Future<void> createTeamMember(_i12.TeamMember? member) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTeamMember,
          [member],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateTeamMember(_i12.TeamMember? member) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTeamMember,
          [member],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteTeamMember(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTeamMember,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deactivateTeamMember(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deactivateTeamMember,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> reactivateTeamMember(String? id) => (super.noSuchMethod(
        Invocation.method(
          #reactivateTeamMember,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i12.TeamMember>> getTeamMembersByRole(String? roleKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTeamMembersByRole,
          [roleKey],
        ),
        returnValue:
            _i5.Future<List<_i12.TeamMember>>.value(<_i12.TeamMember>[]),
      ) as _i5.Future<List<_i12.TeamMember>>);

  @override
  _i5.Future<List<_i12.TeamMember>> getAvailableTeamMembers(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableTeamMembers,
          [date],
        ),
        returnValue:
            _i5.Future<List<_i12.TeamMember>>.value(<_i12.TeamMember>[]),
      ) as _i5.Future<List<_i12.TeamMember>>);

  @override
  _i5.Future<List<_i12.TeamMember>> getQualifiedAvailableMembers(
    String? roleKey,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQualifiedAvailableMembers,
          [
            roleKey,
            date,
          ],
        ),
        returnValue:
            _i5.Future<List<_i12.TeamMember>>.value(<_i12.TeamMember>[]),
      ) as _i5.Future<List<_i12.TeamMember>>);

  @override
  _i5.Future<List<_i12.TeamMember>> searchTeamMembers(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTeamMembers,
          [query],
        ),
        returnValue:
            _i5.Future<List<_i12.TeamMember>>.value(<_i12.TeamMember>[]),
      ) as _i5.Future<List<_i12.TeamMember>>);

  @override
  _i5.Future<void> importTeamMembers(List<_i12.TeamMember>? members) =>
      (super.noSuchMethod(
        Invocation.method(
          #importTeamMembers,
          [members],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Map<String, int>> getStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getStatistics,
          [],
        ),
        returnValue: _i5.Future<Map<String, int>>.value(<String, int>{}),
      ) as _i5.Future<Map<String, int>>);
}

/// A class which mocks [RoleRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRoleRepository extends _i1.Mock implements _i13.RoleRepository {
  MockRoleRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<_i14.Role>> watchRoles() => (super.noSuchMethod(
        Invocation.method(
          #watchRoles,
          [],
        ),
        returnValue: _i5.Stream<List<_i14.Role>>.empty(),
      ) as _i5.Stream<List<_i14.Role>>);

  @override
  _i5.Future<List<_i14.Role>> getAllRoles() => (super.noSuchMethod(
        Invocation.method(
          #getAllRoles,
          [],
        ),
        returnValue: _i5.Future<List<_i14.Role>>.value(<_i14.Role>[]),
      ) as _i5.Future<List<_i14.Role>>);

  @override
  _i5.Future<List<_i14.Role>> getActiveRoles() => (super.noSuchMethod(
        Invocation.method(
          #getActiveRoles,
          [],
        ),
        returnValue: _i5.Future<List<_i14.Role>>.value(<_i14.Role>[]),
      ) as _i5.Future<List<_i14.Role>>);

  @override
  _i5.Future<List<_i14.Role>> getArchivedRoles() => (super.noSuchMethod(
        Invocation.method(
          #getArchivedRoles,
          [],
        ),
        returnValue: _i5.Future<List<_i14.Role>>.value(<_i14.Role>[]),
      ) as _i5.Future<List<_i14.Role>>);

  @override
  _i5.Future<List<_i14.Role>> getVisibleRoles() => (super.noSuchMethod(
        Invocation.method(
          #getVisibleRoles,
          [],
        ),
        returnValue: _i5.Future<List<_i14.Role>>.value(<_i14.Role>[]),
      ) as _i5.Future<List<_i14.Role>>);

  @override
  _i5.Future<_i14.Role?> getRoleById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getRoleById,
          [id],
        ),
        returnValue: _i5.Future<_i14.Role?>.value(),
      ) as _i5.Future<_i14.Role?>);

  @override
  _i5.Future<_i14.Role?> getRoleByKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getRoleByKey,
          [key],
        ),
        returnValue: _i5.Future<_i14.Role?>.value(),
      ) as _i5.Future<_i14.Role?>);

  @override
  _i5.Future<void> createRole({
    required String? hebrewName,
    bool? isVisible = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRole,
          [],
          {
            #hebrewName: hebrewName,
            #isVisible: isVisible,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateRole(_i14.Role? role) => (super.noSuchMethod(
        Invocation.method(
          #updateRole,
          [role],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> renameRole(
    String? roleId,
    String? newHebrewName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #renameRole,
          [
            roleId,
            newHebrewName,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> toggleVisibility(String? roleId) => (super.noSuchMethod(
        Invocation.method(
          #toggleVisibility,
          [roleId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> archiveRole(String? roleId) => (super.noSuchMethod(
        Invocation.method(
          #archiveRole,
          [roleId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> restoreRole(String? roleId) => (super.noSuchMethod(
        Invocation.method(
          #restoreRole,
          [roleId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteRole(String? roleId) => (super.noSuchMethod(
        Invocation.method(
          #deleteRole,
          [roleId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> reorderRoles(List<_i14.Role>? reorderedRoles) =>
      (super.noSuchMethod(
        Invocation.method(
          #reorderRoles,
          [reorderedRoles],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> seedRolesFromEnum() => (super.noSuchMethod(
        Invocation.method(
          #seedRolesFromEnum,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
