import 'package:equatable/equatable.dart';
import '../../../../domain/entities/slot_annotation.dart';

/// A pending gap-annotation edit for one slot, staged until Save — the
/// annotation-world parallel of `StagedAssignmentChange`. Keyed in the bloc by
/// the grid slotKey `"<eventId>_<roleType>_<slotIndex>"`.
class StagedSlotAnnotation extends Equatable {
  final String eventId;
  final String roleType;
  final int slotIndex;

  /// Desired final annotation for this slot; null = the slot should have NO
  /// annotation (a delete on Save).
  final SlotAnnotation? desired;

  /// The reconciled annotation this slot showed when first staged (revert
  /// target — a revert to it drops the entry).
  final SlotAnnotation? baseline;

  /// For a re-key MOVE: the old `"<roleType>#<idx>"` annotation key to delete in
  /// the same Save write. Null for a plain edit/delete.
  final String? staleKey;

  /// Provenance: true when this entry was generated by the quota-driven
  /// auto-cleanup (`_stageSlotAnnotationCleanup`); false when it came from a
  /// user's dialog edit (`_onStageSlotAnnotation`). Lets the cleanup safely
  /// retract its OWN stale entries (e.g. an orphan-delete that a later quota
  /// raise makes unnecessary again) without ever touching a user's edit.
  final bool auto;

  const StagedSlotAnnotation({
    required this.eventId,
    required this.roleType,
    required this.slotIndex,
    required this.desired,
    required this.baseline,
    this.staleKey,
    this.auto = false,
  });

  /// True when the desired note+label equal the baseline — the USER changed
  /// nothing. Unlike [isNoop] this IGNORES [staleKey]: re-keying a drifted
  /// stored key is the quota auto-cleanup's job, NOT something a user's
  /// unchanged Save should stage. Used by `_onStageSlotAnnotation` so that
  /// reopening a drifted note and pressing שמירה without editing never lights
  /// the row up as dirty just to self-heal the key.
  bool get isContentNoop => desired == baseline;

  /// Reverts to baseline AND carries no move → nothing to save, drop it. Used
  /// by the auto-cleanup (`_stageSlotAnnotationCleanup`), which OWNS drift
  /// re-keying: a pure re-key (content unchanged but [staleKey] set) is
  /// intentionally NOT a noop here, so a quota change still heals the DB key.
  bool get isNoop => isContentNoop && staleKey == null;

  Map<String, dynamic> toJson() => {
        'eventId': eventId,
        'roleType': roleType,
        'slotIndex': slotIndex,
        'desired': desired?.toJson(),
        'baseline': baseline?.toJson(),
        'staleKey': staleKey,
        'auto': auto,
      };

  factory StagedSlotAnnotation.fromJson(Map<String, dynamic> json) =>
      StagedSlotAnnotation(
        eventId: json['eventId'] as String,
        roleType: json['roleType'] as String,
        slotIndex: json['slotIndex'] as int,
        desired: json['desired'] == null
            ? null
            : SlotAnnotation.fromJson(
                Map<String, dynamic>.from(json['desired'] as Map)),
        baseline: json['baseline'] == null
            ? null
            : SlotAnnotation.fromJson(
                Map<String, dynamic>.from(json['baseline'] as Map)),
        staleKey: json['staleKey'] as String?,
        // Tolerate old cache blobs written before this field existed.
        auto: (json['auto'] as bool?) ?? false,
      );

  @override
  List<Object?> get props =>
      [eventId, roleType, slotIndex, desired, baseline, staleKey, auto];
}
