// File generated by FlutterFire CLI.
// This file should be version controlled.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBumNcnFydJm__1E_WMIc3R3pmoVF2ABqU',
    appId: '1:890538853278:web:8e66ba1ffe27dc0f154c8f',
    messagingSenderId: '890538853278',
    projectId: 'tsevet-shir-shavtzak',
    authDomain: 'tsevet-shir-shavtzak.firebaseapp.com',
    storageBucket: 'tsevet-shir-shavtzak.firebasestorage.app',
    measurementId: 'G-JK2M1RXGGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBumNcnFydJm__1E_WMIc3R3pmoVF2ABqU',
    appId: '1:890538853278:android:8e66ba1ffe27dc0f154c8f',
    messagingSenderId: '890538853278',
    projectId: 'tsevet-shir-shavtzak',
    storageBucket: 'tsevet-shir-shavtzak.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBumNcnFydJm__1E_WMIc3R3pmoVF2ABqU',
    appId: '1:890538853278:ios:8e66ba1ffe27dc0f154c8f',
    messagingSenderId: '890538853278',
    projectId: 'tsevet-shir-shavtzak',
    storageBucket: 'tsevet-shir-shavtzak.firebasestorage.app',
    iosBundleId: 'com.tsevet.shir.shavtzak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBumNcnFydJm__1E_WMIc3R3pmoVF2ABqU',
    appId: '1:890538853278:ios:8e66ba1ffe27dc0f154c8f',
    messagingSenderId: '890538853278',
    projectId: 'tsevet-shir-shavtzak',
    storageBucket: 'tsevet-shir-shavtzak.firebasestorage.app',
    iosBundleId: 'com.tsevet.shir.shavtzak',
  );
}