// Mocks generated by Mockito 5.4.6 from annotations
// in shavtzak/test/data/repositories/event_repository_reconcile_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:shavtzak/core/constants/calendar_constants.dart' as _i11;
import 'package:shavtzak/core/constants/constraint_status.dart' as _i12;
import 'package:shavtzak/core/services/drive_service.dart' as _i2;
import 'package:shavtzak/data/data_sources/database_interface.dart' as _i3;
import 'package:shavtzak/domain/entities/assignment.dart' as _i9;
import 'package:shavtzak/domain/entities/assignment_label.dart' as _i10;
import 'package:shavtzak/domain/entities/category.dart' as _i16;
import 'package:shavtzak/domain/entities/checklist_item.dart' as _i13;
import 'package:shavtzak/domain/entities/event.dart' as _i7;
import 'package:shavtzak/domain/entities/preset.dart' as _i14;
import 'package:shavtzak/domain/entities/role.dart' as _i15;
import 'package:shavtzak/domain/entities/slot_annotation.dart' as _i8;
import 'package:shavtzak/domain/entities/team_member.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCreateFolderResult_0 extends _i1.SmartFake
    implements _i2.CreateFolderResult {
  _FakeCreateFolderResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeListFilesResult_1 extends _i1.SmartFake
    implements _i2.ListFilesResult {
  _FakeListFilesResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DatabaseInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseInterface extends _i1.Mock implements _i3.DatabaseInterface {
  MockDatabaseInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.TeamMember>> getTeamMembers() => (super.noSuchMethod(
        Invocation.method(
          #getTeamMembers,
          [],
        ),
        returnValue: _i4.Future<List<_i5.TeamMember>>.value(<_i5.TeamMember>[]),
      ) as _i4.Future<List<_i5.TeamMember>>);

  @override
  _i4.Stream<List<_i5.TeamMember>> watchTeamMembers() => (super.noSuchMethod(
        Invocation.method(
          #watchTeamMembers,
          [],
        ),
        returnValue: _i4.Stream<List<_i5.TeamMember>>.empty(),
      ) as _i4.Stream<List<_i5.TeamMember>>);

  @override
  _i4.Future<_i5.TeamMember?> getTeamMemberById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTeamMemberById,
          [id],
        ),
        returnValue: _i4.Future<_i5.TeamMember?>.value(),
      ) as _i4.Future<_i5.TeamMember?>);

  @override
  _i4.Future<_i5.TeamMember?> getTeamMemberByUniqueKey(String? uniqueKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTeamMemberByUniqueKey,
          [uniqueKey],
        ),
        returnValue: _i4.Future<_i5.TeamMember?>.value(),
      ) as _i4.Future<_i5.TeamMember?>);

  @override
  _i4.Future<void> insertTeamMember(_i5.TeamMember? member) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertTeamMember,
          [member],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateTeamMember(_i5.TeamMember? member) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTeamMember,
          [member],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateTeamMemberPasscode(
    String? id,
    String? passcode,
    int? length,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTeamMemberPasscode,
          [
            id,
            passcode,
            length,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearTeamMemberPasscode(String? id) => (super.noSuchMethod(
        Invocation.method(
          #clearTeamMemberPasscode,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String> ensureCalendarFeedToken(String? id) => (super.noSuchMethod(
        Invocation.method(
          #ensureCalendarFeedToken,
          [id],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #ensureCalendarFeedToken,
            [id],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> rotateCalendarFeedToken(String? id) => (super.noSuchMethod(
        Invocation.method(
          #rotateCalendarFeedToken,
          [id],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #rotateCalendarFeedToken,
            [id],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> deleteTeamMember(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTeamMember,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.Event>> getEvents() => (super.noSuchMethod(
        Invocation.method(
          #getEvents,
          [],
        ),
        returnValue: _i4.Future<List<_i7.Event>>.value(<_i7.Event>[]),
      ) as _i4.Future<List<_i7.Event>>);

  @override
  _i4.Stream<List<_i7.Event>> watchEvents() => (super.noSuchMethod(
        Invocation.method(
          #watchEvents,
          [],
        ),
        returnValue: _i4.Stream<List<_i7.Event>>.empty(),
      ) as _i4.Stream<List<_i7.Event>>);

  @override
  _i4.Future<_i7.Event?> getEventById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getEventById,
          [id],
        ),
        returnValue: _i4.Future<_i7.Event?>.value(),
      ) as _i4.Future<_i7.Event?>);

  @override
  _i4.Future<void> insertEvent(_i7.Event? event) => (super.noSuchMethod(
        Invocation.method(
          #insertEvent,
          [event],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateEvent(_i7.Event? event) => (super.noSuchMethod(
        Invocation.method(
          #updateEvent,
          [event],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateEventSlotAnnotation(
    String? eventId,
    String? key,
    _i8.SlotAnnotation? value, {
    String? staleKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEventSlotAnnotation,
          [
            eventId,
            key,
            value,
          ],
          {#staleKey: staleKey},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteEvent(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteEvent,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.Event>> getUpcomingEvents() => (super.noSuchMethod(
        Invocation.method(
          #getUpcomingEvents,
          [],
        ),
        returnValue: _i4.Future<List<_i7.Event>>.value(<_i7.Event>[]),
      ) as _i4.Future<List<_i7.Event>>);

  @override
  _i4.Future<List<_i7.Event>> getEventsByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsByDateRange,
          [
            start,
            end,
          ],
        ),
        returnValue: _i4.Future<List<_i7.Event>>.value(<_i7.Event>[]),
      ) as _i4.Future<List<_i7.Event>>);

  @override
  _i4.Future<List<_i7.Event>> getEventsBeforeDate(
    DateTime? cursor, {
    required int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsBeforeDate,
          [cursor],
          {#limit: limit},
        ),
        returnValue: _i4.Future<List<_i7.Event>>.value(<_i7.Event>[]),
      ) as _i4.Future<List<_i7.Event>>);

  @override
  _i4.Stream<List<_i7.Event>> watchEventsByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchEventsByDateRange,
          [
            start,
            end,
          ],
        ),
        returnValue: _i4.Stream<List<_i7.Event>>.empty(),
      ) as _i4.Stream<List<_i7.Event>>);

  @override
  _i4.Future<bool> isDuplicateEvent(
    String? name,
    DateTime? startDate, {
    String? excludeEventId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #isDuplicateEvent,
          [
            name,
            startDate,
          ],
          {#excludeEventId: excludeEventId},
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<List<_i9.Assignment>> getAssignments() => (super.noSuchMethod(
        Invocation.method(
          #getAssignments,
          [],
        ),
        returnValue: _i4.Future<List<_i9.Assignment>>.value(<_i9.Assignment>[]),
      ) as _i4.Future<List<_i9.Assignment>>);

  @override
  _i4.Stream<List<_i9.Assignment>> watchAssignments() => (super.noSuchMethod(
        Invocation.method(
          #watchAssignments,
          [],
        ),
        returnValue: _i4.Stream<List<_i9.Assignment>>.empty(),
      ) as _i4.Stream<List<_i9.Assignment>>);

  @override
  _i4.Stream<List<_i9.Assignment>> watchAssignmentsByEvent(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAssignmentsByEvent,
          [eventId],
        ),
        returnValue: _i4.Stream<List<_i9.Assignment>>.empty(),
      ) as _i4.Stream<List<_i9.Assignment>>);

  @override
  _i4.Stream<List<_i9.Assignment>> watchAssignmentsByPerson(
          String? teamMemberId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAssignmentsByPerson,
          [teamMemberId],
        ),
        returnValue: _i4.Stream<List<_i9.Assignment>>.empty(),
      ) as _i4.Stream<List<_i9.Assignment>>);

  @override
  _i4.Future<_i9.Assignment?> getAssignmentById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssignmentById,
          [id],
        ),
        returnValue: _i4.Future<_i9.Assignment?>.value(),
      ) as _i4.Future<_i9.Assignment?>);

  @override
  _i4.Future<List<_i9.Assignment>> getAssignmentsByEvent(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssignmentsByEvent,
          [eventId],
        ),
        returnValue: _i4.Future<List<_i9.Assignment>>.value(<_i9.Assignment>[]),
      ) as _i4.Future<List<_i9.Assignment>>);

  @override
  _i4.Future<List<_i9.Assignment>> getAssignmentsByPerson(
          String? teamMemberId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssignmentsByPerson,
          [teamMemberId],
        ),
        returnValue: _i4.Future<List<_i9.Assignment>>.value(<_i9.Assignment>[]),
      ) as _i4.Future<List<_i9.Assignment>>);

  @override
  _i4.Future<List<_i9.Assignment>> getAssignmentsByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssignmentsByDateRange,
          [
            start,
            end,
          ],
        ),
        returnValue: _i4.Future<List<_i9.Assignment>>.value(<_i9.Assignment>[]),
      ) as _i4.Future<List<_i9.Assignment>>);

  @override
  _i4.Future<List<_i9.Assignment>> getAssignmentsInTimeWindow(
    DateTime? windowStart,
    DateTime? windowEnd,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssignmentsInTimeWindow,
          [
            windowStart,
            windowEnd,
          ],
        ),
        returnValue: _i4.Future<List<_i9.Assignment>>.value(<_i9.Assignment>[]),
      ) as _i4.Future<List<_i9.Assignment>>);

  @override
  _i4.Future<List<_i9.Assignment>> getAssignmentsByEventIds(
          List<String>? eventIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssignmentsByEventIds,
          [eventIds],
        ),
        returnValue: _i4.Future<List<_i9.Assignment>>.value(<_i9.Assignment>[]),
      ) as _i4.Future<List<_i9.Assignment>>);

  @override
  _i4.Stream<List<_i9.Assignment>> watchAssignmentsInTimeWindow(
    DateTime? windowStart,
    DateTime? windowEnd,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAssignmentsInTimeWindow,
          [
            windowStart,
            windowEnd,
          ],
        ),
        returnValue: _i4.Stream<List<_i9.Assignment>>.empty(),
      ) as _i4.Stream<List<_i9.Assignment>>);

  @override
  _i4.Future<void> insertAssignment(
    _i9.Assignment? assignment, {
    bool? bypassAvailability,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertAssignment,
          [assignment],
          {#bypassAvailability: bypassAvailability},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateAssignment(
    _i9.Assignment? assignment, {
    bool? bypassAvailability,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAssignment,
          [assignment],
          {#bypassAvailability: bypassAvailability},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateAssignmentMetadata(
    String? assignmentId, {
    required String? notes,
    String? semanticLabelId,
    String? alternativePhoneNumber,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAssignmentMetadata,
          [assignmentId],
          {
            #notes: notes,
            #semanticLabelId: semanticLabelId,
            #alternativePhoneNumber: alternativePhoneNumber,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAssignment(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteAssignment,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAssignmentsByEvent(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAssignmentsByEvent,
          [eventId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAssignmentsByPerson(String? teamMemberId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAssignmentsByPerson,
          [teamMemberId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAssignmentsBatch(List<String>? assignmentIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAssignmentsBatch,
          [assignmentIds],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i10.AssignmentLabel>> getAssignmentLabels() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssignmentLabels,
          [],
        ),
        returnValue: _i4.Future<List<_i10.AssignmentLabel>>.value(
            <_i10.AssignmentLabel>[]),
      ) as _i4.Future<List<_i10.AssignmentLabel>>);

  @override
  _i4.Future<void> insertAssignmentLabel(_i10.AssignmentLabel? label) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertAssignmentLabel,
          [label],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateAssignmentLabel(_i10.AssignmentLabel? label) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAssignmentLabel,
          [label],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> archiveAssignmentLabel(String? id) => (super.noSuchMethod(
        Invocation.method(
          #archiveAssignmentLabel,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> restoreAssignmentLabel(String? id) => (super.noSuchMethod(
        Invocation.method(
          #restoreAssignmentLabel,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAssignmentLabel(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteAssignmentLabel,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateAssignmentLabelsSortOrder(
          Map<String, int>? labelIdToSortOrder) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAssignmentLabelsSortOrder,
          [labelIdToSortOrder],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<List<_i10.AssignmentLabel>> watchAssignmentLabels() =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAssignmentLabels,
          [],
        ),
        returnValue: _i4.Stream<List<_i10.AssignmentLabel>>.empty(),
      ) as _i4.Stream<List<_i10.AssignmentLabel>>);

  @override
  _i4.Future<void> insertTeamMembersBatch(List<_i5.TeamMember>? members) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertTeamMembersBatch,
          [members],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> insertEventsBatch(List<_i7.Event>? events) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertEventsBatch,
          [events],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> insertAssignmentsBatch(List<_i9.Assignment>? assignments) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertAssignmentsBatch,
          [assignments],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveAssignmentsBatch({
    required List<_i9.Assignment>? creates,
    required List<_i9.Assignment>? updates,
    required List<String>? deletes,
    List<({int count, String eventId, String roleType})>? eventQuotaBumps,
    List<({String eventId, int expected, String roleType, int target})>?
        eventQuotaSets,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAssignmentsBatch,
          [],
          {
            #creates: creates,
            #updates: updates,
            #deletes: deletes,
            #eventQuotaBumps: eventQuotaBumps,
            #eventQuotaSets: eventQuotaSets,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveCalendarSyncState({
    required String? constraintId,
    required String? calendarEventId,
    required String? teamMemberId,
    required _i11.CalendarSyncStatus? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCalendarSyncState,
          [],
          {
            #constraintId: constraintId,
            #calendarEventId: calendarEventId,
            #teamMemberId: teamMemberId,
            #status: status,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getCalendarEventId(String? constraintId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCalendarEventId,
          [constraintId],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<Map<String, dynamic>?> getCalendarSyncState(
          String? constraintId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCalendarSyncState,
          [constraintId],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<void> updateCalendarSyncStatus(
    String? constraintId,
    _i11.CalendarSyncStatus? status, {
    String? errorMessage,
    int? retryCount,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCalendarSyncStatus,
          [
            constraintId,
            status,
          ],
          {
            #errorMessage: errorMessage,
            #retryCount: retryCount,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeCalendarSyncState(String? constraintId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeCalendarSyncState,
          [constraintId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>?> atomicCheckAndSetSyncState(
    String? constraintId,
    String? teamMemberId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #atomicCheckAndSetSyncState,
          [
            constraintId,
            teamMemberId,
          ],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getFailedSyncStates() =>
      (super.noSuchMethod(
        Invocation.method(
          #getFailedSyncStates,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getSyncedConstraintsForAllMembers() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSyncedConstraintsForAllMembers,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> saveEventCalendarSyncState({
    required String? eventId,
    required String? assemblyCalendarEventId,
    required String? mainCalendarEventId,
    required _i11.CalendarSyncStatus? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveEventCalendarSyncState,
          [],
          {
            #eventId: eventId,
            #assemblyCalendarEventId: assemblyCalendarEventId,
            #mainCalendarEventId: mainCalendarEventId,
            #status: status,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>?> getEventCalendarSyncState(
          String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventCalendarSyncState,
          [eventId],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Stream<Map<String, _i11.CalendarSyncStatus>>
      watchEventCalendarSyncStates() => (super.noSuchMethod(
            Invocation.method(
              #watchEventCalendarSyncStates,
              [],
            ),
            returnValue:
                _i4.Stream<Map<String, _i11.CalendarSyncStatus>>.empty(),
          ) as _i4.Stream<Map<String, _i11.CalendarSyncStatus>>);

  @override
  _i4.Future<void> removeEventCalendarSyncState(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeEventCalendarSyncState,
          [eventId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateConstraintStatus(
    String? teamMemberIdOrConstraintId,
    int? constraintIndex,
    _i12.ConstraintStatus? newStatus, {
    String? note,
    bool? wasAutoRejectedFromCalendar,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateConstraintStatus,
          [
            teamMemberIdOrConstraintId,
            constraintIndex,
            newStatus,
          ],
          {
            #note: note,
            #wasAutoRejectedFromCalendar: wasAutoRejectedFromCalendar,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addConstraint(
    String? teamMemberId,
    _i5.DateConstraint? newConstraint,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addConstraint,
          [
            teamMemberId,
            newConstraint,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> editConstraintById(
    String? teamMemberId,
    String? constraintId,
    _i5.DateConstraint? updatedConstraint,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #editConstraintById,
          [
            teamMemberId,
            constraintId,
            updatedConstraint,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.DateConstraint?> removeConstraintById(
    String? teamMemberId,
    String? constraintId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeConstraintById,
          [
            teamMemberId,
            constraintId,
          ],
        ),
        returnValue: _i4.Future<_i5.DateConstraint?>.value(),
      ) as _i4.Future<_i5.DateConstraint?>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getSyncedConstraintsForMember(
          String? teamMemberId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSyncedConstraintsForMember,
          [teamMemberId],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, String?>?> getGoogleCalendarConfig() =>
      (super.noSuchMethod(
        Invocation.method(
          #getGoogleCalendarConfig,
          [],
        ),
        returnValue: _i4.Future<Map<String, String?>?>.value(),
      ) as _i4.Future<Map<String, String?>?>);

  @override
  _i4.Future<Map<String, String?>?> getDriveConfig() => (super.noSuchMethod(
        Invocation.method(
          #getDriveConfig,
          [],
        ),
        returnValue: _i4.Future<Map<String, String?>?>.value(),
      ) as _i4.Future<Map<String, String?>?>);

  @override
  _i4.Future<List<_i13.ChecklistItem>> getChecklistItems() =>
      (super.noSuchMethod(
        Invocation.method(
          #getChecklistItems,
          [],
        ),
        returnValue:
            _i4.Future<List<_i13.ChecklistItem>>.value(<_i13.ChecklistItem>[]),
      ) as _i4.Future<List<_i13.ChecklistItem>>);

  @override
  _i4.Future<_i13.ChecklistItem?> getChecklistItemById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChecklistItemById,
          [id],
        ),
        returnValue: _i4.Future<_i13.ChecklistItem?>.value(),
      ) as _i4.Future<_i13.ChecklistItem?>);

  @override
  _i4.Future<List<_i13.ChecklistItem>> getChecklistItemsByEvent(
          String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChecklistItemsByEvent,
          [eventId],
        ),
        returnValue:
            _i4.Future<List<_i13.ChecklistItem>>.value(<_i13.ChecklistItem>[]),
      ) as _i4.Future<List<_i13.ChecklistItem>>);

  @override
  _i4.Future<List<_i13.ChecklistItem>> getChecklistItemsForTeamMember(
          String? teamMemberId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChecklistItemsForTeamMember,
          [teamMemberId],
        ),
        returnValue:
            _i4.Future<List<_i13.ChecklistItem>>.value(<_i13.ChecklistItem>[]),
      ) as _i4.Future<List<_i13.ChecklistItem>>);

  @override
  _i4.Future<List<_i13.ChecklistItem>> getChecklistItemsWhereResponsible(
          String? teamMemberId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChecklistItemsWhereResponsible,
          [teamMemberId],
        ),
        returnValue:
            _i4.Future<List<_i13.ChecklistItem>>.value(<_i13.ChecklistItem>[]),
      ) as _i4.Future<List<_i13.ChecklistItem>>);

  @override
  _i4.Future<List<_i13.ChecklistItem>> getChecklistItemsWhereCc(
          String? teamMemberId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChecklistItemsWhereCc,
          [teamMemberId],
        ),
        returnValue:
            _i4.Future<List<_i13.ChecklistItem>>.value(<_i13.ChecklistItem>[]),
      ) as _i4.Future<List<_i13.ChecklistItem>>);

  @override
  _i4.Future<void> insertChecklistItem(_i13.ChecklistItem? item) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertChecklistItem,
          [item],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateChecklistItem(_i13.ChecklistItem? item) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateChecklistItem,
          [item],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteChecklistItem(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteChecklistItem,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteChecklistItemsByEvent(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteChecklistItemsByEvent,
          [eventId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addNoteToChecklistItem(
    String? checklistItemId,
    Map<String, dynamic>? noteData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addNoteToChecklistItem,
          [
            checklistItemId,
            noteData,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i14.Preset>> getPresets() => (super.noSuchMethod(
        Invocation.method(
          #getPresets,
          [],
        ),
        returnValue: _i4.Future<List<_i14.Preset>>.value(<_i14.Preset>[]),
      ) as _i4.Future<List<_i14.Preset>>);

  @override
  _i4.Future<_i14.Preset?> getPresetById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getPresetById,
          [id],
        ),
        returnValue: _i4.Future<_i14.Preset?>.value(),
      ) as _i4.Future<_i14.Preset?>);

  @override
  _i4.Future<void> insertPreset(_i14.Preset? preset) => (super.noSuchMethod(
        Invocation.method(
          #insertPreset,
          [preset],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updatePreset(_i14.Preset? preset) => (super.noSuchMethod(
        Invocation.method(
          #updatePreset,
          [preset],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deletePreset(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deletePreset,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> loadPresetIntoEvent(
    String? presetId,
    String? eventId,
    String? creatorAdminId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadPresetIntoEvent,
          [
            presetId,
            eventId,
            creatorAdminId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i15.Role>> getRoles() => (super.noSuchMethod(
        Invocation.method(
          #getRoles,
          [],
        ),
        returnValue: _i4.Future<List<_i15.Role>>.value(<_i15.Role>[]),
      ) as _i4.Future<List<_i15.Role>>);

  @override
  _i4.Future<_i15.Role?> getRoleById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getRoleById,
          [id],
        ),
        returnValue: _i4.Future<_i15.Role?>.value(),
      ) as _i4.Future<_i15.Role?>);

  @override
  _i4.Future<_i15.Role?> getRoleByKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getRoleByKey,
          [key],
        ),
        returnValue: _i4.Future<_i15.Role?>.value(),
      ) as _i4.Future<_i15.Role?>);

  @override
  _i4.Future<void> insertRole(_i15.Role? role) => (super.noSuchMethod(
        Invocation.method(
          #insertRole,
          [role],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateRole(_i15.Role? role) => (super.noSuchMethod(
        Invocation.method(
          #updateRole,
          [role],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> archiveRole(String? id) => (super.noSuchMethod(
        Invocation.method(
          #archiveRole,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> restoreRole(String? id) => (super.noSuchMethod(
        Invocation.method(
          #restoreRole,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteRole(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteRole,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<List<_i15.Role>> watchRoles() => (super.noSuchMethod(
        Invocation.method(
          #watchRoles,
          [],
        ),
        returnValue: _i4.Stream<List<_i15.Role>>.empty(),
      ) as _i4.Stream<List<_i15.Role>>);

  @override
  _i4.Future<void> seedRolesFromEnum() => (super.noSuchMethod(
        Invocation.method(
          #seedRolesFromEnum,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateRolesSortOrder(Map<String, int>? roleIdToSortOrder) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRolesSortOrder,
          [roleIdToSortOrder],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i16.Category>> getCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue: _i4.Future<List<_i16.Category>>.value(<_i16.Category>[]),
      ) as _i4.Future<List<_i16.Category>>);

  @override
  _i4.Future<List<_i16.Category>> getActiveCategories() => (super.noSuchMethod(
        Invocation.method(
          #getActiveCategories,
          [],
        ),
        returnValue: _i4.Future<List<_i16.Category>>.value(<_i16.Category>[]),
      ) as _i4.Future<List<_i16.Category>>);

  @override
  _i4.Future<_i16.Category?> getCategoryById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getCategoryById,
          [id],
        ),
        returnValue: _i4.Future<_i16.Category?>.value(),
      ) as _i4.Future<_i16.Category?>);

  @override
  _i4.Future<void> insertCategory(_i16.Category? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertCategory,
          [category],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateCategory(_i16.Category? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategory,
          [category],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteCategory(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCategory,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> permanentlyDeleteCategory(String? id) => (super.noSuchMethod(
        Invocation.method(
          #permanentlyDeleteCategory,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> restoreCategory(String? id) => (super.noSuchMethod(
        Invocation.method(
          #restoreCategory,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<List<_i16.Category>> watchCategories() => (super.noSuchMethod(
        Invocation.method(
          #watchCategories,
          [],
        ),
        returnValue: _i4.Stream<List<_i16.Category>>.empty(),
      ) as _i4.Stream<List<_i16.Category>>);

  @override
  _i4.Stream<List<_i16.Category>> watchActiveCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #watchActiveCategories,
          [],
        ),
        returnValue: _i4.Stream<List<_i16.Category>>.empty(),
      ) as _i4.Stream<List<_i16.Category>>);
}

/// A class which mocks [DriveService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDriveService extends _i1.Mock implements _i2.DriveService {
  MockDriveService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  void initialize() => super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<_i2.CreateFolderResult> createFolder({
    required String? eventName,
    required DateTime? date,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFolder,
          [],
          {
            #eventName: eventName,
            #date: date,
            #endDate: endDate,
          },
        ),
        returnValue:
            _i4.Future<_i2.CreateFolderResult>.value(_FakeCreateFolderResult_0(
          this,
          Invocation.method(
            #createFolder,
            [],
            {
              #eventName: eventName,
              #date: date,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i4.Future<_i2.CreateFolderResult>);

  @override
  _i4.Future<bool> renameFolder({
    required String? folderId,
    required String? newName,
    required DateTime? newDate,
    DateTime? newEndDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #renameFolder,
          [],
          {
            #folderId: folderId,
            #newName: newName,
            #newDate: newDate,
            #newEndDate: newEndDate,
          },
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> deleteFolder({required String? folderId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFolder,
          [],
          {#folderId: folderId},
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i2.ListFilesResult> listFiles({required String? folderId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #listFiles,
          [],
          {#folderId: folderId},
        ),
        returnValue:
            _i4.Future<_i2.ListFilesResult>.value(_FakeListFilesResult_1(
          this,
          Invocation.method(
            #listFiles,
            [],
            {#folderId: folderId},
          ),
        )),
      ) as _i4.Future<_i2.ListFilesResult>);
}
