// Mocks generated by Mockito 5.4.6 from annotations
// in shavtzak/test/presentation/screens/event/category_management_dialog_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:shavtzak/core/constants/calendar_constants.dart' as _i7;
import 'package:shavtzak/core/constants/role_types.dart' as _i10;
import 'package:shavtzak/core/services/drive_service.dart' as _i9;
import 'package:shavtzak/data/repositories/category_repository.dart' as _i4;
import 'package:shavtzak/data/repositories/event_repository.dart' as _i6;
import 'package:shavtzak/domain/entities/assignment.dart' as _i11;
import 'package:shavtzak/domain/entities/category.dart' as _i2;
import 'package:shavtzak/domain/entities/event.dart' as _i3;
import 'package:shavtzak/domain/entities/slot_annotation.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCategory_0 extends _i1.SmartFake implements _i2.Category {
  _FakeCategory_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEvent_1 extends _i1.SmartFake implements _i3.Event {
  _FakeEvent_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i4.CategoryRepository {
  MockCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<_i2.Category>> watchCategories() => (super.noSuchMethod(
        Invocation.method(
          #watchCategories,
          [],
        ),
        returnValue: _i5.Stream<List<_i2.Category>>.empty(),
      ) as _i5.Stream<List<_i2.Category>>);

  @override
  _i5.Stream<List<_i2.Category>> watchActiveCategories() => (super.noSuchMethod(
        Invocation.method(
          #watchActiveCategories,
          [],
        ),
        returnValue: _i5.Stream<List<_i2.Category>>.empty(),
      ) as _i5.Stream<List<_i2.Category>>);

  @override
  _i5.Future<List<_i2.Category>> getCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue: _i5.Future<List<_i2.Category>>.value(<_i2.Category>[]),
      ) as _i5.Future<List<_i2.Category>>);

  @override
  _i5.Future<List<_i2.Category>> getActiveCategories() => (super.noSuchMethod(
        Invocation.method(
          #getActiveCategories,
          [],
        ),
        returnValue: _i5.Future<List<_i2.Category>>.value(<_i2.Category>[]),
      ) as _i5.Future<List<_i2.Category>>);

  @override
  _i5.Future<_i2.Category> createCategory(
    String? name, {
    int? sortOrder,
    int? colorValue,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCategory,
          [name],
          {
            #sortOrder: sortOrder,
            #colorValue: colorValue,
          },
        ),
        returnValue: _i5.Future<_i2.Category>.value(_FakeCategory_0(
          this,
          Invocation.method(
            #createCategory,
            [name],
            {
              #sortOrder: sortOrder,
              #colorValue: colorValue,
            },
          ),
        )),
      ) as _i5.Future<_i2.Category>);

  @override
  _i5.Future<_i2.Category> updateCategory(_i2.Category? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategory,
          [category],
        ),
        returnValue: _i5.Future<_i2.Category>.value(_FakeCategory_0(
          this,
          Invocation.method(
            #updateCategory,
            [category],
          ),
        )),
      ) as _i5.Future<_i2.Category>);

  @override
  _i5.Future<_i2.Category> renameCategory(
    String? categoryId,
    String? newName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #renameCategory,
          [
            categoryId,
            newName,
          ],
        ),
        returnValue: _i5.Future<_i2.Category>.value(_FakeCategory_0(
          this,
          Invocation.method(
            #renameCategory,
            [
              categoryId,
              newName,
            ],
          ),
        )),
      ) as _i5.Future<_i2.Category>);

  @override
  _i5.Future<void> deleteCategory(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCategory,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> permanentlyDeleteCategory(String? id) => (super.noSuchMethod(
        Invocation.method(
          #permanentlyDeleteCategory,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> restoreCategory(String? id) => (super.noSuchMethod(
        Invocation.method(
          #restoreCategory,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> reorderCategories(List<_i2.Category>? categories) =>
      (super.noSuchMethod(
        Invocation.method(
          #reorderCategories,
          [categories],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [EventRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventRepository extends _i1.Mock implements _i6.EventRepository {
  MockEventRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<_i3.Event>> watchEvents() => (super.noSuchMethod(
        Invocation.method(
          #watchEvents,
          [],
        ),
        returnValue: _i5.Stream<List<_i3.Event>>.empty(),
      ) as _i5.Stream<List<_i3.Event>>);

  @override
  _i5.Stream<Map<String, _i7.CalendarSyncStatus>>
      watchEventCalendarSyncStates() => (super.noSuchMethod(
            Invocation.method(
              #watchEventCalendarSyncStates,
              [],
            ),
            returnValue:
                _i5.Stream<Map<String, _i7.CalendarSyncStatus>>.empty(),
          ) as _i5.Stream<Map<String, _i7.CalendarSyncStatus>>);

  @override
  _i5.Stream<List<_i3.Event>> watchEventsByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchEventsByDateRange,
          [
            start,
            end,
          ],
        ),
        returnValue: _i5.Stream<List<_i3.Event>>.empty(),
      ) as _i5.Stream<List<_i3.Event>>);

  @override
  _i5.Future<List<_i3.Event>> getAllEvents() => (super.noSuchMethod(
        Invocation.method(
          #getAllEvents,
          [],
        ),
        returnValue: _i5.Future<List<_i3.Event>>.value(<_i3.Event>[]),
      ) as _i5.Future<List<_i3.Event>>);

  @override
  _i5.Future<_i3.Event?> getEventById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getEventById,
          [id],
        ),
        returnValue: _i5.Future<_i3.Event?>.value(),
      ) as _i5.Future<_i3.Event?>);

  @override
  _i5.Future<List<_i3.Event>> getUpcomingEvents() => (super.noSuchMethod(
        Invocation.method(
          #getUpcomingEvents,
          [],
        ),
        returnValue: _i5.Future<List<_i3.Event>>.value(<_i3.Event>[]),
      ) as _i5.Future<List<_i3.Event>>);

  @override
  _i5.Future<List<_i3.Event>> getEventsByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsByDateRange,
          [
            start,
            end,
          ],
        ),
        returnValue: _i5.Future<List<_i3.Event>>.value(<_i3.Event>[]),
      ) as _i5.Future<List<_i3.Event>>);

  @override
  _i5.Future<List<_i3.Event>> getEventsBeforeDate(
    DateTime? cursor, {
    required int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsBeforeDate,
          [cursor],
          {#limit: limit},
        ),
        returnValue: _i5.Future<List<_i3.Event>>.value(<_i3.Event>[]),
      ) as _i5.Future<List<_i3.Event>>);

  @override
  _i5.Future<List<_i3.Event>> getEventsOnDate(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsOnDate,
          [date],
        ),
        returnValue: _i5.Future<List<_i3.Event>>.value(<_i3.Event>[]),
      ) as _i5.Future<List<_i3.Event>>);

  @override
  _i5.Future<bool> isDuplicateEvent(
    String? name,
    DateTime? startDate, {
    String? excludeEventId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #isDuplicateEvent,
          [
            name,
            startDate,
          ],
          {#excludeEventId: excludeEventId},
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i3.Event> createEvent(_i3.Event? event) => (super.noSuchMethod(
        Invocation.method(
          #createEvent,
          [event],
        ),
        returnValue: _i5.Future<_i3.Event>.value(_FakeEvent_1(
          this,
          Invocation.method(
            #createEvent,
            [event],
          ),
        )),
      ) as _i5.Future<_i3.Event>);

  @override
  _i5.Future<_i3.Event> updateEvent(
    _i3.Event? event, {
    _i3.Event? knownOriginal,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEvent,
          [event],
          {#knownOriginal: knownOriginal},
        ),
        returnValue: _i5.Future<_i3.Event>.value(_FakeEvent_1(
          this,
          Invocation.method(
            #updateEvent,
            [event],
            {#knownOriginal: knownOriginal},
          ),
        )),
      ) as _i5.Future<_i3.Event>);

  @override
  _i5.Future<void> updateSlotAnnotation(
    String? eventId,
    String? key,
    _i8.SlotAnnotation? value, {
    String? staleKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSlotAnnotation,
          [
            eventId,
            key,
            value,
          ],
          {#staleKey: staleKey},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteEvent(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteEvent,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i9.DriveFile>> getEventFiles(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventFiles,
          [eventId],
        ),
        returnValue: _i5.Future<List<_i9.DriveFile>>.value(<_i9.DriveFile>[]),
      ) as _i5.Future<List<_i9.DriveFile>>);

  @override
  _i5.Future<List<_i3.Event>> searchEvents(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchEvents,
          [query],
        ),
        returnValue: _i5.Future<List<_i3.Event>>.value(<_i3.Event>[]),
      ) as _i5.Future<List<_i3.Event>>);

  @override
  _i5.Future<List<_i3.Event>> getEventsRequiringRole(_i10.RoleType? role) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsRequiringRole,
          [role],
        ),
        returnValue: _i5.Future<List<_i3.Event>>.value(<_i3.Event>[]),
      ) as _i5.Future<List<_i3.Event>>);

  @override
  _i5.Future<void> importEvents(List<_i3.Event>? events) => (super.noSuchMethod(
        Invocation.method(
          #importEvents,
          [events],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Map<String, int>> getStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getStatistics,
          [],
        ),
        returnValue: _i5.Future<Map<String, int>>.value(<String, int>{}),
      ) as _i5.Future<Map<String, int>>);

  @override
  _i5.Future<List<_i3.Event>> getCurrentMonthEvents() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentMonthEvents,
          [],
        ),
        returnValue: _i5.Future<List<_i3.Event>>.value(<_i3.Event>[]),
      ) as _i5.Future<List<_i3.Event>>);

  @override
  _i5.Future<List<_i3.Event>> getThisWeekEvents() => (super.noSuchMethod(
        Invocation.method(
          #getThisWeekEvents,
          [],
        ),
        returnValue: _i5.Future<List<_i3.Event>>.value(<_i3.Event>[]),
      ) as _i5.Future<List<_i3.Event>>);

  @override
  _i5.Future<void> duplicateEvent(
    _i3.Event? originalEvent,
    _i3.Event? newEvent,
    List<_i11.Assignment>? originalAssignments,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #duplicateEvent,
          [
            originalEvent,
            newEvent,
            originalAssignments,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Map<String, _i11.Assignment>> duplicateEventWithAssignmentIds(
    _i3.Event? originalEvent,
    _i3.Event? newEvent,
    List<_i11.Assignment>? originalAssignments,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #duplicateEventWithAssignmentIds,
          [
            originalEvent,
            newEvent,
            originalAssignments,
          ],
        ),
        returnValue: _i5.Future<Map<String, _i11.Assignment>>.value(
            <String, _i11.Assignment>{}),
      ) as _i5.Future<Map<String, _i11.Assignment>>);

  @override
  _i5.Future<void> removeAssignmentsAfterDuplication(
          List<String>? assignmentIdsToRemove) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeAssignmentsAfterDuplication,
          [assignmentIdsToRemove],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i9.CreateFolderResult?> ensureDriveFolder(_i3.Event? event) =>
      (super.noSuchMethod(
        Invocation.method(
          #ensureDriveFolder,
          [event],
        ),
        returnValue: _i5.Future<_i9.CreateFolderResult?>.value(),
      ) as _i5.Future<_i9.CreateFolderResult?>);
}
