name: Deploy website

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
          channel: 'stable'
      
      - name: Install dependencies
        working-directory: shavtzak
        run: flutter pub get

      - name: Build for web
        working-directory: shavtzak
        run: flutter build web --release --base-href /Shavtzak/ --pwa-strategy=none

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./shavtzak/build/web
